// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowEmu.Data.Db;

#nullable disable

namespace WowEmu.Data.Db.Migrations.Characters
{
    [DbContext(typeof(CharactersDbContext))]
    [Migration("20260804200229_InitialCharactersSchema")]
    partial class InitialCharactersSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WowEmu.Data.Db.CharacterEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("AccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("account_id");

                    b.Property<ushort>("AtLoginFlags")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("at_login_flags");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("class");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<byte>("Face")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("face");

                    b.Property<byte>("FacialStyle")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("facial_style");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("gender");

                    b.Property<uint>("GuildId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guild_id");

                    b.Property<byte>("HairColor")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("hair_color");

                    b.Property<byte>("HairStyle")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("hair_style");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("level");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned")
                        .HasColumnName("map");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_bin");

                    b.Property<float>("Orientation")
                        .HasColumnType("float")
                        .HasColumnName("orientation");

                    b.Property<uint>("PlayerFlags")
                        .HasColumnType("int unsigned")
                        .HasColumnName("player_flags");

                    b.Property<float>("PositionX")
                        .HasColumnType("float")
                        .HasColumnName("position_x");

                    b.Property<float>("PositionY")
                        .HasColumnType("float")
                        .HasColumnName("position_y");

                    b.Property<float>("PositionZ")
                        .HasColumnType("float")
                        .HasColumnName("position_z");

                    b.Property<byte>("Race")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("race");

                    b.Property<byte>("Skin")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("skin");

                    b.Property<uint>("Zone")
                        .HasColumnType("int unsigned")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_characters_name");

                    b.ToTable("characters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
