// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowEmu.Data.Db;

#nullable disable

namespace WowEmu.Data.Db.Migrations.Characters
{
    [DbContext(typeof(CharactersDbContext))]
    [Migration("20260807195531_CharacterTalents")]
    partial class CharacterTalents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WowEmu.Data.Db.CharacterActionEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<byte>("Button")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("button");

                    b.Property<uint>("Action")
                        .HasColumnType("int unsigned")
                        .HasColumnName("action");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("type");

                    b.HasKey("CharacterId", "Button");

                    b.ToTable("character_action", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("AccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("account_id");

                    b.Property<byte>("ActiveSpec")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("activeTalentGroup");

                    b.Property<ushort>("AtLoginFlags")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("at_login_flags");

                    b.Property<uint>("ChosenTitle")
                        .HasColumnType("int unsigned")
                        .HasColumnName("chosenTitle");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("class");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("DeathExpireTime")
                        .HasColumnType("bigint")
                        .HasColumnName("death_expire_time");

                    b.Property<uint>("Experience")
                        .HasColumnType("int unsigned")
                        .HasColumnName("xp");

                    b.Property<byte>("Face")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("face");

                    b.Property<byte>("FacialStyle")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("facial_style");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("gender");

                    b.Property<uint>("GuildId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guild_id");

                    b.Property<byte>("HairColor")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("hair_color");

                    b.Property<byte>("HairStyle")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("hair_style");

                    b.Property<uint>("Health")
                        .HasColumnType("int unsigned")
                        .HasColumnName("health");

                    b.Property<string>("KnownTitles")
                        .HasColumnType("longtext")
                        .HasColumnName("knownTitles");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("level");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned")
                        .HasColumnName("map");

                    b.Property<uint>("Money")
                        .HasColumnType("int unsigned")
                        .HasColumnName("money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_bin");

                    b.Property<float>("Orientation")
                        .HasColumnType("float")
                        .HasColumnName("orientation");

                    b.Property<uint>("PlayerFlags")
                        .HasColumnType("int unsigned")
                        .HasColumnName("player_flags");

                    b.Property<float>("PositionX")
                        .HasColumnType("float")
                        .HasColumnName("position_x");

                    b.Property<float>("PositionY")
                        .HasColumnType("float")
                        .HasColumnName("position_y");

                    b.Property<float>("PositionZ")
                        .HasColumnType("float")
                        .HasColumnName("position_z");

                    b.Property<uint>("Power1")
                        .HasColumnType("int unsigned")
                        .HasColumnName("power1");

                    b.Property<uint>("Power2")
                        .HasColumnType("int unsigned")
                        .HasColumnName("power2");

                    b.Property<uint>("Power3")
                        .HasColumnType("int unsigned")
                        .HasColumnName("power3");

                    b.Property<uint>("Power4")
                        .HasColumnType("int unsigned")
                        .HasColumnName("power4");

                    b.Property<uint>("Power5")
                        .HasColumnType("int unsigned")
                        .HasColumnName("power5");

                    b.Property<uint>("Power6")
                        .HasColumnType("int unsigned")
                        .HasColumnName("power6");

                    b.Property<uint>("Power7")
                        .HasColumnType("int unsigned")
                        .HasColumnName("power7");

                    b.Property<byte>("Race")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("race");

                    b.Property<uint>("ResetTalentsCost")
                        .HasColumnType("int unsigned")
                        .HasColumnName("resettalents_cost");

                    b.Property<long>("ResetTalentsTime")
                        .HasColumnType("bigint")
                        .HasColumnName("resettalents_time");

                    b.Property<byte>("Skin")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("skin");

                    b.Property<byte>("SpecCount")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("specCount");

                    b.Property<uint>("Zone")
                        .HasColumnType("int unsigned")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_characters_name");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterGlyphEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<byte>("Spec")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("talentGroup");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("slot");

                    b.Property<uint>("GlyphId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("glyph");

                    b.HasKey("CharacterId", "Spec", "Slot");

                    b.ToTable("character_glyphs", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterHomebindEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("AreaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("zoneId");

                    b.Property<uint>("MapId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("mapId");

                    b.Property<float>("PositionX")
                        .HasColumnType("float")
                        .HasColumnName("posX");

                    b.Property<float>("PositionY")
                        .HasColumnType("float")
                        .HasColumnName("posY");

                    b.Property<float>("PositionZ")
                        .HasColumnType("float")
                        .HasColumnName("posZ");

                    b.HasKey("CharacterId");

                    b.ToTable("character_homebind", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterInventoryEntity", b =>
                {
                    b.Property<uint>("ItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("item");

                    b.Property<uint>("BagId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("bag");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("slot");

                    b.HasKey("ItemId");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_inventory_owner");

                    b.ToTable("character_inventory", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterQuestDailyEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("QuestId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("quest");

                    b.HasKey("CharacterId", "QuestId");

                    b.ToTable("character_queststatus_daily", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterQuestEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("QuestId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("quest");

                    b.Property<ushort>("Killed1")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("mobcount1");

                    b.Property<ushort>("Killed2")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("mobcount2");

                    b.Property<ushort>("Killed3")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("mobcount3");

                    b.Property<ushort>("Killed4")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("mobcount4");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("slot");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.HasKey("CharacterId", "QuestId");

                    b.ToTable("character_queststatus", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterQuestMonthlyEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("QuestId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("quest");

                    b.HasKey("CharacterId", "QuestId");

                    b.ToTable("character_queststatus_monthly", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterQuestWeeklyEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("QuestId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("quest");

                    b.HasKey("CharacterId", "QuestId");

                    b.ToTable("character_queststatus_weekly", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterReputationEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<ushort>("FactionId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("faction");

                    b.Property<int>("Standing")
                        .HasColumnType("int")
                        .HasColumnName("standing");

                    b.HasKey("CharacterId", "FactionId");

                    b.ToTable("character_reputation", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterSkillEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<ushort>("SkillId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("skill");

                    b.Property<ushort>("MaxValue")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("max");

                    b.Property<ushort>("Step")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("step");

                    b.Property<ushort>("Value")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("value");

                    b.HasKey("CharacterId", "SkillId");

                    b.ToTable("character_skills", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterSpellEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("SpellId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("spell");

                    b.HasKey("CharacterId", "SpellId");

                    b.ToTable("character_spell", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.CharacterTalentEntity", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<byte>("Spec")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("talentGroup");

                    b.Property<uint>("TalentId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("talentId");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("rank");

                    b.HasKey("CharacterId", "Spec", "TalentId");

                    b.ToTable("character_talent", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.ItemInstanceEntity", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    b.Property<uint>("Count")
                        .HasColumnType("int unsigned")
                        .HasColumnName("count");

                    b.Property<uint>("Durability")
                        .HasColumnType("int unsigned")
                        .HasColumnName("durability");

                    b.Property<uint>("DurationSeconds")
                        .HasColumnType("int unsigned")
                        .HasColumnName("duration");

                    b.Property<uint>("Entry")
                        .HasColumnType("int unsigned")
                        .HasColumnName("item_entry");

                    b.Property<uint>("Flags")
                        .HasColumnType("int unsigned")
                        .HasColumnName("flags");

                    b.Property<uint>("OwnerId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_guid");

                    b.Property<int>("RandomPropertyId")
                        .HasColumnType("int")
                        .HasColumnName("randomPropertyId");

                    b.Property<string>("SpellCharges")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("charges");

                    b.Property<uint>("SuffixFactor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("randomSuffix");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_item_instance_owner");

                    b.ToTable("item_instance", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
