// <auto-generated>
//     Generated by tools/codegen/generate_update_fields.py from AzerothCore's UpdateFields.h.
//     Do not edit by hand -- regenerate instead.
// </auto-generated>

#nullable enable

namespace WowEmu.Protocol;

/// <summary>
/// How wide a field is and how the client interprets it.
/// </summary>
/// <remarks>
/// <see cref="Long"/> and <see cref="Bytes"/> are the ones that catch people: a LONG occupies two
/// consecutive uint32 slots, and BYTES is four independent bytes packed into one slot, so neither
/// can be written with a plain 32-bit assignment.
/// </remarks>
public enum UpdateFieldType : byte
{
    Int = 0,
    Long,
    Float,
    Bytes,
    TwoShort,
}

/// <summary>
/// Who is allowed to see a field.
/// </summary>
/// <remarks>
/// This is not decoration. The same object is serialized differently per observer: a player sees
/// their own <see cref="Private"/> fields, party members see <see cref="PartyMember"/> ones, and
/// everybody sees <see cref="Public"/>. Treating a private field as public leaks another player's
/// state to everyone nearby.
/// </remarks>
[Flags]
public enum UpdateFieldFlag : byte
{
    None = 0x00,
    Public = 0x01,
    Private = 0x02,
    Owner = 0x04,
    ItemOwner = 0x08,
    PartyMember = 0x10,
    PartyLeader = 0x20,
    Dynamic = 0x40,
}

/// <summary>Metadata for one update field.</summary>
public readonly record struct UpdateFieldInfo(
    string Name,
    int Index,
    int Size,
    UpdateFieldType Type,
    UpdateFieldFlag Flags);

/// <summary>
/// Update-field indices, transcribed from the 3.3.5a client's layout.
/// </summary>
/// <remarks>
/// Indices are into a flat <c>uint[]</c>. They are cumulative across the object hierarchy: unit
/// fields start where object fields end, player fields where unit fields end. The <c>*_END</c>
/// values are therefore both the end of one block and the base of the next.
/// </remarks>
public static class UpdateFields
{
    /// <summary>Index 0.</summary>
    public const int OBJECT_FIELD_GUID = 0;

    /// <summary>Index 2.</summary>
    public const int OBJECT_FIELD_TYPE = 2;

    /// <summary>Index 3.</summary>
    public const int OBJECT_FIELD_ENTRY = 3;

    /// <summary>Index 4.</summary>
    public const int OBJECT_FIELD_SCALE_X = 4;

    /// <summary>Index 5.</summary>
    public const int OBJECT_FIELD_PADDING = 5;

    /// <summary>Index 6.</summary>
    public const int OBJECT_END = 6;

    /// <summary>Index 6.</summary>
    public const int ITEM_FIELD_OWNER = 6;

    /// <summary>Index 8.</summary>
    public const int ITEM_FIELD_CONTAINED = 8;

    /// <summary>Index 10.</summary>
    public const int ITEM_FIELD_CREATOR = 10;

    /// <summary>Index 12.</summary>
    public const int ITEM_FIELD_GIFTCREATOR = 12;

    /// <summary>Index 14.</summary>
    public const int ITEM_FIELD_STACK_COUNT = 14;

    /// <summary>Index 15.</summary>
    public const int ITEM_FIELD_DURATION = 15;

    /// <summary>Index 16.</summary>
    public const int ITEM_FIELD_SPELL_CHARGES = 16;

    /// <summary>Index 21.</summary>
    public const int ITEM_FIELD_FLAGS = 21;

    /// <summary>Index 22.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_1_1 = 22;

    /// <summary>Index 24.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_1_3 = 24;

    /// <summary>Index 25.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_2_1 = 25;

    /// <summary>Index 27.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_2_3 = 27;

    /// <summary>Index 28.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_3_1 = 28;

    /// <summary>Index 30.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_3_3 = 30;

    /// <summary>Index 31.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_4_1 = 31;

    /// <summary>Index 33.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_4_3 = 33;

    /// <summary>Index 34.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_5_1 = 34;

    /// <summary>Index 36.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_5_3 = 36;

    /// <summary>Index 37.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_6_1 = 37;

    /// <summary>Index 39.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_6_3 = 39;

    /// <summary>Index 40.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_7_1 = 40;

    /// <summary>Index 42.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_7_3 = 42;

    /// <summary>Index 43.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_8_1 = 43;

    /// <summary>Index 45.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_8_3 = 45;

    /// <summary>Index 46.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_9_1 = 46;

    /// <summary>Index 48.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_9_3 = 48;

    /// <summary>Index 49.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_10_1 = 49;

    /// <summary>Index 51.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_10_3 = 51;

    /// <summary>Index 52.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_11_1 = 52;

    /// <summary>Index 54.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_11_3 = 54;

    /// <summary>Index 55.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_12_1 = 55;

    /// <summary>Index 57.</summary>
    public const int ITEM_FIELD_ENCHANTMENT_12_3 = 57;

    /// <summary>Index 58.</summary>
    public const int ITEM_FIELD_PROPERTY_SEED = 58;

    /// <summary>Index 59.</summary>
    public const int ITEM_FIELD_RANDOM_PROPERTIES_ID = 59;

    /// <summary>Index 60.</summary>
    public const int ITEM_FIELD_DURABILITY = 60;

    /// <summary>Index 61.</summary>
    public const int ITEM_FIELD_MAXDURABILITY = 61;

    /// <summary>Index 62.</summary>
    public const int ITEM_FIELD_CREATE_PLAYED_TIME = 62;

    /// <summary>Index 63.</summary>
    public const int ITEM_FIELD_PAD = 63;

    /// <summary>Index 64.</summary>
    public const int ITEM_END = 64;

    /// <summary>Index 64.</summary>
    public const int CONTAINER_FIELD_NUM_SLOTS = 64;

    /// <summary>Index 65.</summary>
    public const int CONTAINER_ALIGN_PAD = 65;

    /// <summary>Index 66.</summary>
    public const int CONTAINER_FIELD_SLOT_1 = 66;

    /// <summary>Index 138.</summary>
    public const int CONTAINER_END = 138;

    /// <summary>Index 6.</summary>
    public const int UNIT_FIELD_CHARM = 6;

    /// <summary>Index 8.</summary>
    public const int UNIT_FIELD_SUMMON = 8;

    /// <summary>Index 10.</summary>
    public const int UNIT_FIELD_CRITTER = 10;

    /// <summary>Index 12.</summary>
    public const int UNIT_FIELD_CHARMEDBY = 12;

    /// <summary>Index 14.</summary>
    public const int UNIT_FIELD_SUMMONEDBY = 14;

    /// <summary>Index 16.</summary>
    public const int UNIT_FIELD_CREATEDBY = 16;

    /// <summary>Index 18.</summary>
    public const int UNIT_FIELD_TARGET = 18;

    /// <summary>Index 20.</summary>
    public const int UNIT_FIELD_CHANNEL_OBJECT = 20;

    /// <summary>Index 22.</summary>
    public const int UNIT_CHANNEL_SPELL = 22;

    /// <summary>Index 23.</summary>
    public const int UNIT_FIELD_BYTES_0 = 23;

    /// <summary>Index 24.</summary>
    public const int UNIT_FIELD_HEALTH = 24;

    /// <summary>Index 25.</summary>
    public const int UNIT_FIELD_POWER1 = 25;

    /// <summary>Index 26.</summary>
    public const int UNIT_FIELD_POWER2 = 26;

    /// <summary>Index 27.</summary>
    public const int UNIT_FIELD_POWER3 = 27;

    /// <summary>Index 28.</summary>
    public const int UNIT_FIELD_POWER4 = 28;

    /// <summary>Index 29.</summary>
    public const int UNIT_FIELD_POWER5 = 29;

    /// <summary>Index 30.</summary>
    public const int UNIT_FIELD_POWER6 = 30;

    /// <summary>Index 31.</summary>
    public const int UNIT_FIELD_POWER7 = 31;

    /// <summary>Index 32.</summary>
    public const int UNIT_FIELD_MAXHEALTH = 32;

    /// <summary>Index 33.</summary>
    public const int UNIT_FIELD_MAXPOWER1 = 33;

    /// <summary>Index 34.</summary>
    public const int UNIT_FIELD_MAXPOWER2 = 34;

    /// <summary>Index 35.</summary>
    public const int UNIT_FIELD_MAXPOWER3 = 35;

    /// <summary>Index 36.</summary>
    public const int UNIT_FIELD_MAXPOWER4 = 36;

    /// <summary>Index 37.</summary>
    public const int UNIT_FIELD_MAXPOWER5 = 37;

    /// <summary>Index 38.</summary>
    public const int UNIT_FIELD_MAXPOWER6 = 38;

    /// <summary>Index 39.</summary>
    public const int UNIT_FIELD_MAXPOWER7 = 39;

    /// <summary>Index 40.</summary>
    public const int UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER = 40;

    /// <summary>Index 47.</summary>
    public const int UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER = 47;

    /// <summary>Index 54.</summary>
    public const int UNIT_FIELD_LEVEL = 54;

    /// <summary>Index 55.</summary>
    public const int UNIT_FIELD_FACTIONTEMPLATE = 55;

    /// <summary>Index 56.</summary>
    public const int UNIT_VIRTUAL_ITEM_SLOT_ID = 56;

    /// <summary>Index 59.</summary>
    public const int UNIT_FIELD_FLAGS = 59;

    /// <summary>Index 60.</summary>
    public const int UNIT_FIELD_FLAGS_2 = 60;

    /// <summary>Index 61.</summary>
    public const int UNIT_FIELD_AURASTATE = 61;

    /// <summary>Index 62.</summary>
    public const int UNIT_FIELD_BASEATTACKTIME = 62;

    /// <summary>Index 64.</summary>
    public const int UNIT_FIELD_RANGEDATTACKTIME = 64;

    /// <summary>Index 65.</summary>
    public const int UNIT_FIELD_BOUNDINGRADIUS = 65;

    /// <summary>Index 66.</summary>
    public const int UNIT_FIELD_COMBATREACH = 66;

    /// <summary>Index 67.</summary>
    public const int UNIT_FIELD_DISPLAYID = 67;

    /// <summary>Index 68.</summary>
    public const int UNIT_FIELD_NATIVEDISPLAYID = 68;

    /// <summary>Index 69.</summary>
    public const int UNIT_FIELD_MOUNTDISPLAYID = 69;

    /// <summary>Index 70.</summary>
    public const int UNIT_FIELD_MINDAMAGE = 70;

    /// <summary>Index 71.</summary>
    public const int UNIT_FIELD_MAXDAMAGE = 71;

    /// <summary>Index 72.</summary>
    public const int UNIT_FIELD_MINOFFHANDDAMAGE = 72;

    /// <summary>Index 73.</summary>
    public const int UNIT_FIELD_MAXOFFHANDDAMAGE = 73;

    /// <summary>Index 74.</summary>
    public const int UNIT_FIELD_BYTES_1 = 74;

    /// <summary>Index 75.</summary>
    public const int UNIT_FIELD_PETNUMBER = 75;

    /// <summary>Index 76.</summary>
    public const int UNIT_FIELD_PET_NAME_TIMESTAMP = 76;

    /// <summary>Index 77.</summary>
    public const int UNIT_FIELD_PETEXPERIENCE = 77;

    /// <summary>Index 78.</summary>
    public const int UNIT_FIELD_PETNEXTLEVELEXP = 78;

    /// <summary>Index 79.</summary>
    public const int UNIT_DYNAMIC_FLAGS = 79;

    /// <summary>Index 80.</summary>
    public const int UNIT_MOD_CAST_SPEED = 80;

    /// <summary>Index 81.</summary>
    public const int UNIT_CREATED_BY_SPELL = 81;

    /// <summary>Index 82.</summary>
    public const int UNIT_NPC_FLAGS = 82;

    /// <summary>Index 83.</summary>
    public const int UNIT_NPC_EMOTESTATE = 83;

    /// <summary>Index 84.</summary>
    public const int UNIT_FIELD_STAT0 = 84;

    /// <summary>Index 85.</summary>
    public const int UNIT_FIELD_STAT1 = 85;

    /// <summary>Index 86.</summary>
    public const int UNIT_FIELD_STAT2 = 86;

    /// <summary>Index 87.</summary>
    public const int UNIT_FIELD_STAT3 = 87;

    /// <summary>Index 88.</summary>
    public const int UNIT_FIELD_STAT4 = 88;

    /// <summary>Index 89.</summary>
    public const int UNIT_FIELD_POSSTAT0 = 89;

    /// <summary>Index 90.</summary>
    public const int UNIT_FIELD_POSSTAT1 = 90;

    /// <summary>Index 91.</summary>
    public const int UNIT_FIELD_POSSTAT2 = 91;

    /// <summary>Index 92.</summary>
    public const int UNIT_FIELD_POSSTAT3 = 92;

    /// <summary>Index 93.</summary>
    public const int UNIT_FIELD_POSSTAT4 = 93;

    /// <summary>Index 94.</summary>
    public const int UNIT_FIELD_NEGSTAT0 = 94;

    /// <summary>Index 95.</summary>
    public const int UNIT_FIELD_NEGSTAT1 = 95;

    /// <summary>Index 96.</summary>
    public const int UNIT_FIELD_NEGSTAT2 = 96;

    /// <summary>Index 97.</summary>
    public const int UNIT_FIELD_NEGSTAT3 = 97;

    /// <summary>Index 98.</summary>
    public const int UNIT_FIELD_NEGSTAT4 = 98;

    /// <summary>Index 99.</summary>
    public const int UNIT_FIELD_RESISTANCES = 99;

    /// <summary>Index 106.</summary>
    public const int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = 106;

    /// <summary>Index 113.</summary>
    public const int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = 113;

    /// <summary>Index 120.</summary>
    public const int UNIT_FIELD_BASE_MANA = 120;

    /// <summary>Index 121.</summary>
    public const int UNIT_FIELD_BASE_HEALTH = 121;

    /// <summary>Index 122.</summary>
    public const int UNIT_FIELD_BYTES_2 = 122;

    /// <summary>Index 123.</summary>
    public const int UNIT_FIELD_ATTACK_POWER = 123;

    /// <summary>Index 124.</summary>
    public const int UNIT_FIELD_ATTACK_POWER_MODS = 124;

    /// <summary>Index 125.</summary>
    public const int UNIT_FIELD_ATTACK_POWER_MULTIPLIER = 125;

    /// <summary>Index 126.</summary>
    public const int UNIT_FIELD_RANGED_ATTACK_POWER = 126;

    /// <summary>Index 127.</summary>
    public const int UNIT_FIELD_RANGED_ATTACK_POWER_MODS = 127;

    /// <summary>Index 128.</summary>
    public const int UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = 128;

    /// <summary>Index 129.</summary>
    public const int UNIT_FIELD_MINRANGEDDAMAGE = 129;

    /// <summary>Index 130.</summary>
    public const int UNIT_FIELD_MAXRANGEDDAMAGE = 130;

    /// <summary>Index 131.</summary>
    public const int UNIT_FIELD_POWER_COST_MODIFIER = 131;

    /// <summary>Index 138.</summary>
    public const int UNIT_FIELD_POWER_COST_MULTIPLIER = 138;

    /// <summary>Index 145.</summary>
    public const int UNIT_FIELD_MAXHEALTHMODIFIER = 145;

    /// <summary>Index 146.</summary>
    public const int UNIT_FIELD_HOVERHEIGHT = 146;

    /// <summary>Index 147.</summary>
    public const int UNIT_FIELD_PADDING = 147;

    /// <summary>Index 148.</summary>
    public const int UNIT_END = 148;

    /// <summary>Index 148.</summary>
    public const int PLAYER_DUEL_ARBITER = 148;

    /// <summary>Index 150.</summary>
    public const int PLAYER_FLAGS = 150;

    /// <summary>Index 151.</summary>
    public const int PLAYER_GUILDID = 151;

    /// <summary>Index 152.</summary>
    public const int PLAYER_GUILDRANK = 152;

    /// <summary>Index 153.</summary>
    public const int PLAYER_BYTES = 153;

    /// <summary>Index 154.</summary>
    public const int PLAYER_BYTES_2 = 154;

    /// <summary>Index 155.</summary>
    public const int PLAYER_BYTES_3 = 155;

    /// <summary>Index 156.</summary>
    public const int PLAYER_DUEL_TEAM = 156;

    /// <summary>Index 157.</summary>
    public const int PLAYER_GUILD_TIMESTAMP = 157;

    /// <summary>Index 158.</summary>
    public const int PLAYER_QUEST_LOG_1_1 = 158;

    /// <summary>Index 159.</summary>
    public const int PLAYER_QUEST_LOG_1_2 = 159;

    /// <summary>Index 160.</summary>
    public const int PLAYER_QUEST_LOG_1_3 = 160;

    /// <summary>Index 162.</summary>
    public const int PLAYER_QUEST_LOG_1_4 = 162;

    /// <summary>Index 163.</summary>
    public const int PLAYER_QUEST_LOG_2_1 = 163;

    /// <summary>Index 164.</summary>
    public const int PLAYER_QUEST_LOG_2_2 = 164;

    /// <summary>Index 165.</summary>
    public const int PLAYER_QUEST_LOG_2_3 = 165;

    /// <summary>Index 167.</summary>
    public const int PLAYER_QUEST_LOG_2_5 = 167;

    /// <summary>Index 168.</summary>
    public const int PLAYER_QUEST_LOG_3_1 = 168;

    /// <summary>Index 169.</summary>
    public const int PLAYER_QUEST_LOG_3_2 = 169;

    /// <summary>Index 170.</summary>
    public const int PLAYER_QUEST_LOG_3_3 = 170;

    /// <summary>Index 172.</summary>
    public const int PLAYER_QUEST_LOG_3_5 = 172;

    /// <summary>Index 173.</summary>
    public const int PLAYER_QUEST_LOG_4_1 = 173;

    /// <summary>Index 174.</summary>
    public const int PLAYER_QUEST_LOG_4_2 = 174;

    /// <summary>Index 175.</summary>
    public const int PLAYER_QUEST_LOG_4_3 = 175;

    /// <summary>Index 177.</summary>
    public const int PLAYER_QUEST_LOG_4_5 = 177;

    /// <summary>Index 178.</summary>
    public const int PLAYER_QUEST_LOG_5_1 = 178;

    /// <summary>Index 179.</summary>
    public const int PLAYER_QUEST_LOG_5_2 = 179;

    /// <summary>Index 180.</summary>
    public const int PLAYER_QUEST_LOG_5_3 = 180;

    /// <summary>Index 182.</summary>
    public const int PLAYER_QUEST_LOG_5_5 = 182;

    /// <summary>Index 183.</summary>
    public const int PLAYER_QUEST_LOG_6_1 = 183;

    /// <summary>Index 184.</summary>
    public const int PLAYER_QUEST_LOG_6_2 = 184;

    /// <summary>Index 185.</summary>
    public const int PLAYER_QUEST_LOG_6_3 = 185;

    /// <summary>Index 187.</summary>
    public const int PLAYER_QUEST_LOG_6_5 = 187;

    /// <summary>Index 188.</summary>
    public const int PLAYER_QUEST_LOG_7_1 = 188;

    /// <summary>Index 189.</summary>
    public const int PLAYER_QUEST_LOG_7_2 = 189;

    /// <summary>Index 190.</summary>
    public const int PLAYER_QUEST_LOG_7_3 = 190;

    /// <summary>Index 192.</summary>
    public const int PLAYER_QUEST_LOG_7_5 = 192;

    /// <summary>Index 193.</summary>
    public const int PLAYER_QUEST_LOG_8_1 = 193;

    /// <summary>Index 194.</summary>
    public const int PLAYER_QUEST_LOG_8_2 = 194;

    /// <summary>Index 195.</summary>
    public const int PLAYER_QUEST_LOG_8_3 = 195;

    /// <summary>Index 197.</summary>
    public const int PLAYER_QUEST_LOG_8_5 = 197;

    /// <summary>Index 198.</summary>
    public const int PLAYER_QUEST_LOG_9_1 = 198;

    /// <summary>Index 199.</summary>
    public const int PLAYER_QUEST_LOG_9_2 = 199;

    /// <summary>Index 200.</summary>
    public const int PLAYER_QUEST_LOG_9_3 = 200;

    /// <summary>Index 202.</summary>
    public const int PLAYER_QUEST_LOG_9_5 = 202;

    /// <summary>Index 203.</summary>
    public const int PLAYER_QUEST_LOG_10_1 = 203;

    /// <summary>Index 204.</summary>
    public const int PLAYER_QUEST_LOG_10_2 = 204;

    /// <summary>Index 205.</summary>
    public const int PLAYER_QUEST_LOG_10_3 = 205;

    /// <summary>Index 207.</summary>
    public const int PLAYER_QUEST_LOG_10_5 = 207;

    /// <summary>Index 208.</summary>
    public const int PLAYER_QUEST_LOG_11_1 = 208;

    /// <summary>Index 209.</summary>
    public const int PLAYER_QUEST_LOG_11_2 = 209;

    /// <summary>Index 210.</summary>
    public const int PLAYER_QUEST_LOG_11_3 = 210;

    /// <summary>Index 212.</summary>
    public const int PLAYER_QUEST_LOG_11_5 = 212;

    /// <summary>Index 213.</summary>
    public const int PLAYER_QUEST_LOG_12_1 = 213;

    /// <summary>Index 214.</summary>
    public const int PLAYER_QUEST_LOG_12_2 = 214;

    /// <summary>Index 215.</summary>
    public const int PLAYER_QUEST_LOG_12_3 = 215;

    /// <summary>Index 217.</summary>
    public const int PLAYER_QUEST_LOG_12_5 = 217;

    /// <summary>Index 218.</summary>
    public const int PLAYER_QUEST_LOG_13_1 = 218;

    /// <summary>Index 219.</summary>
    public const int PLAYER_QUEST_LOG_13_2 = 219;

    /// <summary>Index 220.</summary>
    public const int PLAYER_QUEST_LOG_13_3 = 220;

    /// <summary>Index 222.</summary>
    public const int PLAYER_QUEST_LOG_13_5 = 222;

    /// <summary>Index 223.</summary>
    public const int PLAYER_QUEST_LOG_14_1 = 223;

    /// <summary>Index 224.</summary>
    public const int PLAYER_QUEST_LOG_14_2 = 224;

    /// <summary>Index 225.</summary>
    public const int PLAYER_QUEST_LOG_14_3 = 225;

    /// <summary>Index 227.</summary>
    public const int PLAYER_QUEST_LOG_14_5 = 227;

    /// <summary>Index 228.</summary>
    public const int PLAYER_QUEST_LOG_15_1 = 228;

    /// <summary>Index 229.</summary>
    public const int PLAYER_QUEST_LOG_15_2 = 229;

    /// <summary>Index 230.</summary>
    public const int PLAYER_QUEST_LOG_15_3 = 230;

    /// <summary>Index 232.</summary>
    public const int PLAYER_QUEST_LOG_15_5 = 232;

    /// <summary>Index 233.</summary>
    public const int PLAYER_QUEST_LOG_16_1 = 233;

    /// <summary>Index 234.</summary>
    public const int PLAYER_QUEST_LOG_16_2 = 234;

    /// <summary>Index 235.</summary>
    public const int PLAYER_QUEST_LOG_16_3 = 235;

    /// <summary>Index 237.</summary>
    public const int PLAYER_QUEST_LOG_16_5 = 237;

    /// <summary>Index 238.</summary>
    public const int PLAYER_QUEST_LOG_17_1 = 238;

    /// <summary>Index 239.</summary>
    public const int PLAYER_QUEST_LOG_17_2 = 239;

    /// <summary>Index 240.</summary>
    public const int PLAYER_QUEST_LOG_17_3 = 240;

    /// <summary>Index 242.</summary>
    public const int PLAYER_QUEST_LOG_17_5 = 242;

    /// <summary>Index 243.</summary>
    public const int PLAYER_QUEST_LOG_18_1 = 243;

    /// <summary>Index 244.</summary>
    public const int PLAYER_QUEST_LOG_18_2 = 244;

    /// <summary>Index 245.</summary>
    public const int PLAYER_QUEST_LOG_18_3 = 245;

    /// <summary>Index 247.</summary>
    public const int PLAYER_QUEST_LOG_18_5 = 247;

    /// <summary>Index 248.</summary>
    public const int PLAYER_QUEST_LOG_19_1 = 248;

    /// <summary>Index 249.</summary>
    public const int PLAYER_QUEST_LOG_19_2 = 249;

    /// <summary>Index 250.</summary>
    public const int PLAYER_QUEST_LOG_19_3 = 250;

    /// <summary>Index 252.</summary>
    public const int PLAYER_QUEST_LOG_19_5 = 252;

    /// <summary>Index 253.</summary>
    public const int PLAYER_QUEST_LOG_20_1 = 253;

    /// <summary>Index 254.</summary>
    public const int PLAYER_QUEST_LOG_20_2 = 254;

    /// <summary>Index 255.</summary>
    public const int PLAYER_QUEST_LOG_20_3 = 255;

    /// <summary>Index 257.</summary>
    public const int PLAYER_QUEST_LOG_20_5 = 257;

    /// <summary>Index 258.</summary>
    public const int PLAYER_QUEST_LOG_21_1 = 258;

    /// <summary>Index 259.</summary>
    public const int PLAYER_QUEST_LOG_21_2 = 259;

    /// <summary>Index 260.</summary>
    public const int PLAYER_QUEST_LOG_21_3 = 260;

    /// <summary>Index 262.</summary>
    public const int PLAYER_QUEST_LOG_21_5 = 262;

    /// <summary>Index 263.</summary>
    public const int PLAYER_QUEST_LOG_22_1 = 263;

    /// <summary>Index 264.</summary>
    public const int PLAYER_QUEST_LOG_22_2 = 264;

    /// <summary>Index 265.</summary>
    public const int PLAYER_QUEST_LOG_22_3 = 265;

    /// <summary>Index 267.</summary>
    public const int PLAYER_QUEST_LOG_22_5 = 267;

    /// <summary>Index 268.</summary>
    public const int PLAYER_QUEST_LOG_23_1 = 268;

    /// <summary>Index 269.</summary>
    public const int PLAYER_QUEST_LOG_23_2 = 269;

    /// <summary>Index 270.</summary>
    public const int PLAYER_QUEST_LOG_23_3 = 270;

    /// <summary>Index 272.</summary>
    public const int PLAYER_QUEST_LOG_23_5 = 272;

    /// <summary>Index 273.</summary>
    public const int PLAYER_QUEST_LOG_24_1 = 273;

    /// <summary>Index 274.</summary>
    public const int PLAYER_QUEST_LOG_24_2 = 274;

    /// <summary>Index 275.</summary>
    public const int PLAYER_QUEST_LOG_24_3 = 275;

    /// <summary>Index 277.</summary>
    public const int PLAYER_QUEST_LOG_24_5 = 277;

    /// <summary>Index 278.</summary>
    public const int PLAYER_QUEST_LOG_25_1 = 278;

    /// <summary>Index 279.</summary>
    public const int PLAYER_QUEST_LOG_25_2 = 279;

    /// <summary>Index 280.</summary>
    public const int PLAYER_QUEST_LOG_25_3 = 280;

    /// <summary>Index 282.</summary>
    public const int PLAYER_QUEST_LOG_25_5 = 282;

    /// <summary>Index 283.</summary>
    public const int PLAYER_VISIBLE_ITEM_1_ENTRYID = 283;

    /// <summary>Index 284.</summary>
    public const int PLAYER_VISIBLE_ITEM_1_ENCHANTMENT = 284;

    /// <summary>Index 285.</summary>
    public const int PLAYER_VISIBLE_ITEM_2_ENTRYID = 285;

    /// <summary>Index 286.</summary>
    public const int PLAYER_VISIBLE_ITEM_2_ENCHANTMENT = 286;

    /// <summary>Index 287.</summary>
    public const int PLAYER_VISIBLE_ITEM_3_ENTRYID = 287;

    /// <summary>Index 288.</summary>
    public const int PLAYER_VISIBLE_ITEM_3_ENCHANTMENT = 288;

    /// <summary>Index 289.</summary>
    public const int PLAYER_VISIBLE_ITEM_4_ENTRYID = 289;

    /// <summary>Index 290.</summary>
    public const int PLAYER_VISIBLE_ITEM_4_ENCHANTMENT = 290;

    /// <summary>Index 291.</summary>
    public const int PLAYER_VISIBLE_ITEM_5_ENTRYID = 291;

    /// <summary>Index 292.</summary>
    public const int PLAYER_VISIBLE_ITEM_5_ENCHANTMENT = 292;

    /// <summary>Index 293.</summary>
    public const int PLAYER_VISIBLE_ITEM_6_ENTRYID = 293;

    /// <summary>Index 294.</summary>
    public const int PLAYER_VISIBLE_ITEM_6_ENCHANTMENT = 294;

    /// <summary>Index 295.</summary>
    public const int PLAYER_VISIBLE_ITEM_7_ENTRYID = 295;

    /// <summary>Index 296.</summary>
    public const int PLAYER_VISIBLE_ITEM_7_ENCHANTMENT = 296;

    /// <summary>Index 297.</summary>
    public const int PLAYER_VISIBLE_ITEM_8_ENTRYID = 297;

    /// <summary>Index 298.</summary>
    public const int PLAYER_VISIBLE_ITEM_8_ENCHANTMENT = 298;

    /// <summary>Index 299.</summary>
    public const int PLAYER_VISIBLE_ITEM_9_ENTRYID = 299;

    /// <summary>Index 300.</summary>
    public const int PLAYER_VISIBLE_ITEM_9_ENCHANTMENT = 300;

    /// <summary>Index 301.</summary>
    public const int PLAYER_VISIBLE_ITEM_10_ENTRYID = 301;

    /// <summary>Index 302.</summary>
    public const int PLAYER_VISIBLE_ITEM_10_ENCHANTMENT = 302;

    /// <summary>Index 303.</summary>
    public const int PLAYER_VISIBLE_ITEM_11_ENTRYID = 303;

    /// <summary>Index 304.</summary>
    public const int PLAYER_VISIBLE_ITEM_11_ENCHANTMENT = 304;

    /// <summary>Index 305.</summary>
    public const int PLAYER_VISIBLE_ITEM_12_ENTRYID = 305;

    /// <summary>Index 306.</summary>
    public const int PLAYER_VISIBLE_ITEM_12_ENCHANTMENT = 306;

    /// <summary>Index 307.</summary>
    public const int PLAYER_VISIBLE_ITEM_13_ENTRYID = 307;

    /// <summary>Index 308.</summary>
    public const int PLAYER_VISIBLE_ITEM_13_ENCHANTMENT = 308;

    /// <summary>Index 309.</summary>
    public const int PLAYER_VISIBLE_ITEM_14_ENTRYID = 309;

    /// <summary>Index 310.</summary>
    public const int PLAYER_VISIBLE_ITEM_14_ENCHANTMENT = 310;

    /// <summary>Index 311.</summary>
    public const int PLAYER_VISIBLE_ITEM_15_ENTRYID = 311;

    /// <summary>Index 312.</summary>
    public const int PLAYER_VISIBLE_ITEM_15_ENCHANTMENT = 312;

    /// <summary>Index 313.</summary>
    public const int PLAYER_VISIBLE_ITEM_16_ENTRYID = 313;

    /// <summary>Index 314.</summary>
    public const int PLAYER_VISIBLE_ITEM_16_ENCHANTMENT = 314;

    /// <summary>Index 315.</summary>
    public const int PLAYER_VISIBLE_ITEM_17_ENTRYID = 315;

    /// <summary>Index 316.</summary>
    public const int PLAYER_VISIBLE_ITEM_17_ENCHANTMENT = 316;

    /// <summary>Index 317.</summary>
    public const int PLAYER_VISIBLE_ITEM_18_ENTRYID = 317;

    /// <summary>Index 318.</summary>
    public const int PLAYER_VISIBLE_ITEM_18_ENCHANTMENT = 318;

    /// <summary>Index 319.</summary>
    public const int PLAYER_VISIBLE_ITEM_19_ENTRYID = 319;

    /// <summary>Index 320.</summary>
    public const int PLAYER_VISIBLE_ITEM_19_ENCHANTMENT = 320;

    /// <summary>Index 321.</summary>
    public const int PLAYER_CHOSEN_TITLE = 321;

    /// <summary>Index 322.</summary>
    public const int PLAYER_FAKE_INEBRIATION = 322;

    /// <summary>Index 323.</summary>
    public const int PLAYER_FIELD_PAD_0 = 323;

    /// <summary>Index 324.</summary>
    public const int PLAYER_FIELD_INV_SLOT_HEAD = 324;

    /// <summary>Index 370.</summary>
    public const int PLAYER_FIELD_PACK_SLOT_1 = 370;

    /// <summary>Index 402.</summary>
    public const int PLAYER_FIELD_BANK_SLOT_1 = 402;

    /// <summary>Index 458.</summary>
    public const int PLAYER_FIELD_BANKBAG_SLOT_1 = 458;

    /// <summary>Index 472.</summary>
    public const int PLAYER_FIELD_VENDORBUYBACK_SLOT_1 = 472;

    /// <summary>Index 496.</summary>
    public const int PLAYER_FIELD_KEYRING_SLOT_1 = 496;

    /// <summary>Index 560.</summary>
    public const int PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 = 560;

    /// <summary>Index 624.</summary>
    public const int PLAYER_FARSIGHT = 624;

    /// <summary>Index 626.</summary>
    public const int PLAYER__FIELD_KNOWN_TITLES = 626;

    /// <summary>Index 628.</summary>
    public const int PLAYER__FIELD_KNOWN_TITLES1 = 628;

    /// <summary>Index 630.</summary>
    public const int PLAYER__FIELD_KNOWN_TITLES2 = 630;

    /// <summary>Index 632.</summary>
    public const int PLAYER_FIELD_KNOWN_CURRENCIES = 632;

    /// <summary>Index 634.</summary>
    public const int PLAYER_XP = 634;

    /// <summary>Index 635.</summary>
    public const int PLAYER_NEXT_LEVEL_XP = 635;

    /// <summary>Index 636.</summary>
    public const int PLAYER_SKILL_INFO_1_1 = 636;

    /// <summary>Index 1020.</summary>
    public const int PLAYER_CHARACTER_POINTS1 = 1020;

    /// <summary>Index 1021.</summary>
    public const int PLAYER_CHARACTER_POINTS2 = 1021;

    /// <summary>Index 1022.</summary>
    public const int PLAYER_TRACK_CREATURES = 1022;

    /// <summary>Index 1023.</summary>
    public const int PLAYER_TRACK_RESOURCES = 1023;

    /// <summary>Index 1024.</summary>
    public const int PLAYER_BLOCK_PERCENTAGE = 1024;

    /// <summary>Index 1025.</summary>
    public const int PLAYER_DODGE_PERCENTAGE = 1025;

    /// <summary>Index 1026.</summary>
    public const int PLAYER_PARRY_PERCENTAGE = 1026;

    /// <summary>Index 1027.</summary>
    public const int PLAYER_EXPERTISE = 1027;

    /// <summary>Index 1028.</summary>
    public const int PLAYER_OFFHAND_EXPERTISE = 1028;

    /// <summary>Index 1029.</summary>
    public const int PLAYER_CRIT_PERCENTAGE = 1029;

    /// <summary>Index 1030.</summary>
    public const int PLAYER_RANGED_CRIT_PERCENTAGE = 1030;

    /// <summary>Index 1031.</summary>
    public const int PLAYER_OFFHAND_CRIT_PERCENTAGE = 1031;

    /// <summary>Index 1032.</summary>
    public const int PLAYER_SPELL_CRIT_PERCENTAGE1 = 1032;

    /// <summary>Index 1039.</summary>
    public const int PLAYER_SHIELD_BLOCK = 1039;

    /// <summary>Index 1040.</summary>
    public const int PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE = 1040;

    /// <summary>Index 1041.</summary>
    public const int PLAYER_EXPLORED_ZONES_1 = 1041;

    /// <summary>Index 1169.</summary>
    public const int PLAYER_REST_STATE_EXPERIENCE = 1169;

    /// <summary>Index 1170.</summary>
    public const int PLAYER_FIELD_COINAGE = 1170;

    /// <summary>Index 1171.</summary>
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_POS = 1171;

    /// <summary>Index 1178.</summary>
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG = 1178;

    /// <summary>Index 1185.</summary>
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT = 1185;

    /// <summary>Index 1192.</summary>
    public const int PLAYER_FIELD_MOD_HEALING_DONE_POS = 1192;

    /// <summary>Index 1193.</summary>
    public const int PLAYER_FIELD_MOD_HEALING_PCT = 1193;

    /// <summary>Index 1194.</summary>
    public const int PLAYER_FIELD_MOD_HEALING_DONE_PCT = 1194;

    /// <summary>Index 1195.</summary>
    public const int PLAYER_FIELD_MOD_TARGET_RESISTANCE = 1195;

    /// <summary>Index 1196.</summary>
    public const int PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = 1196;

    /// <summary>Index 1197.</summary>
    public const int PLAYER_FIELD_BYTES = 1197;

    /// <summary>Index 1198.</summary>
    public const int PLAYER_AMMO_ID = 1198;

    /// <summary>Index 1199.</summary>
    public const int PLAYER_SELF_RES_SPELL = 1199;

    /// <summary>Index 1200.</summary>
    public const int PLAYER_FIELD_PVP_MEDALS = 1200;

    /// <summary>Index 1201.</summary>
    public const int PLAYER_FIELD_BUYBACK_PRICE_1 = 1201;

    /// <summary>Index 1213.</summary>
    public const int PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = 1213;

    /// <summary>Index 1225.</summary>
    public const int PLAYER_FIELD_KILLS = 1225;

    /// <summary>Index 1226.</summary>
    public const int PLAYER_FIELD_TODAY_CONTRIBUTION = 1226;

    /// <summary>Index 1227.</summary>
    public const int PLAYER_FIELD_YESTERDAY_CONTRIBUTION = 1227;

    /// <summary>Index 1228.</summary>
    public const int PLAYER_FIELD_LIFETIME_HONORABLE_KILLS = 1228;

    /// <summary>Index 1229.</summary>
    public const int PLAYER_FIELD_BYTES2 = 1229;

    /// <summary>Index 1230.</summary>
    public const int PLAYER_FIELD_WATCHED_FACTION_INDEX = 1230;

    /// <summary>Index 1231.</summary>
    public const int PLAYER_FIELD_COMBAT_RATING_1 = 1231;

    /// <summary>Index 1256.</summary>
    public const int PLAYER_FIELD_ARENA_TEAM_INFO_1_1 = 1256;

    /// <summary>Index 1277.</summary>
    public const int PLAYER_FIELD_HONOR_CURRENCY = 1277;

    /// <summary>Index 1278.</summary>
    public const int PLAYER_FIELD_ARENA_CURRENCY = 1278;

    /// <summary>Index 1279.</summary>
    public const int PLAYER_FIELD_MAX_LEVEL = 1279;

    /// <summary>Index 1280.</summary>
    public const int PLAYER_FIELD_DAILY_QUESTS_1 = 1280;

    /// <summary>Index 1305.</summary>
    public const int PLAYER_RUNE_REGEN_1 = 1305;

    /// <summary>Index 1309.</summary>
    public const int PLAYER_NO_REAGENT_COST_1 = 1309;

    /// <summary>Index 1312.</summary>
    public const int PLAYER_FIELD_GLYPH_SLOTS_1 = 1312;

    /// <summary>Index 1318.</summary>
    public const int PLAYER_FIELD_GLYPHS_1 = 1318;

    /// <summary>Index 1324.</summary>
    public const int PLAYER_GLYPHS_ENABLED = 1324;

    /// <summary>Index 1325.</summary>
    public const int PLAYER_PET_SPELL_POWER = 1325;

    /// <summary>Index 1326.</summary>
    public const int PLAYER_END = 1326;

    /// <summary>Index 6.</summary>
    public const int OBJECT_FIELD_CREATED_BY = 6;

    /// <summary>Index 8.</summary>
    public const int GAMEOBJECT_DISPLAYID = 8;

    /// <summary>Index 9.</summary>
    public const int GAMEOBJECT_FLAGS = 9;

    /// <summary>Index 10.</summary>
    public const int GAMEOBJECT_PARENTROTATION = 10;

    /// <summary>Index 14.</summary>
    public const int GAMEOBJECT_DYNAMIC = 14;

    /// <summary>Index 15.</summary>
    public const int GAMEOBJECT_FACTION = 15;

    /// <summary>Index 16.</summary>
    public const int GAMEOBJECT_LEVEL = 16;

    /// <summary>Index 17.</summary>
    public const int GAMEOBJECT_BYTES_1 = 17;

    /// <summary>Index 18.</summary>
    public const int GAMEOBJECT_END = 18;

    /// <summary>Index 6.</summary>
    public const int DYNAMICOBJECT_CASTER = 6;

    /// <summary>Index 8.</summary>
    public const int DYNAMICOBJECT_BYTES = 8;

    /// <summary>Index 9.</summary>
    public const int DYNAMICOBJECT_SPELLID = 9;

    /// <summary>Index 10.</summary>
    public const int DYNAMICOBJECT_RADIUS = 10;

    /// <summary>Index 11.</summary>
    public const int DYNAMICOBJECT_CASTTIME = 11;

    /// <summary>Index 12.</summary>
    public const int DYNAMICOBJECT_END = 12;

    /// <summary>Index 6.</summary>
    public const int CORPSE_FIELD_OWNER = 6;

    /// <summary>Index 8.</summary>
    public const int CORPSE_FIELD_PARTY = 8;

    /// <summary>Index 10.</summary>
    public const int CORPSE_FIELD_DISPLAY_ID = 10;

    /// <summary>Index 11.</summary>
    public const int CORPSE_FIELD_ITEM = 11;

    /// <summary>Index 30.</summary>
    public const int CORPSE_FIELD_BYTES_1 = 30;

    /// <summary>Index 31.</summary>
    public const int CORPSE_FIELD_BYTES_2 = 31;

    /// <summary>Index 32.</summary>
    public const int CORPSE_FIELD_GUILD = 32;

    /// <summary>Index 33.</summary>
    public const int CORPSE_FIELD_FLAGS = 33;

    /// <summary>Index 34.</summary>
    public const int CORPSE_FIELD_DYNAMIC_FLAGS = 34;

    /// <summary>Index 35.</summary>
    public const int CORPSE_FIELD_PAD = 35;

    /// <summary>Index 36.</summary>
    public const int CORPSE_END = 36;

    private static readonly UpdateFieldInfo[] AllFields =
    [
        new("OBJECT_FIELD_GUID", 0, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("OBJECT_FIELD_TYPE", 2, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("OBJECT_FIELD_ENTRY", 3, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("OBJECT_FIELD_SCALE_X", 4, 1, UpdateFieldType.Float, UpdateFieldFlag.Public),
        new("OBJECT_FIELD_PADDING", 5, 1, UpdateFieldType.Int, UpdateFieldFlag.None),
        new("ITEM_FIELD_OWNER", 6, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("ITEM_FIELD_CONTAINED", 8, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("ITEM_FIELD_CREATOR", 10, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("ITEM_FIELD_GIFTCREATOR", 12, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("ITEM_FIELD_STACK_COUNT", 14, 1, UpdateFieldType.Int, UpdateFieldFlag.Owner | UpdateFieldFlag.ItemOwner),
        new("ITEM_FIELD_DURATION", 15, 1, UpdateFieldType.Int, UpdateFieldFlag.Owner | UpdateFieldFlag.ItemOwner),
        new("ITEM_FIELD_SPELL_CHARGES", 16, 5, UpdateFieldType.Int, UpdateFieldFlag.Owner | UpdateFieldFlag.ItemOwner),
        new("ITEM_FIELD_FLAGS", 21, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_1_1", 22, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_1_3", 24, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_2_1", 25, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_2_3", 27, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_3_1", 28, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_3_3", 30, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_4_1", 31, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_4_3", 33, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_5_1", 34, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_5_3", 36, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_6_1", 37, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_6_3", 39, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_7_1", 40, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_7_3", 42, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_8_1", 43, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_8_3", 45, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_9_1", 46, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_9_3", 48, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_10_1", 49, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_10_3", 51, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_11_1", 52, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_11_3", 54, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_12_1", 55, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_ENCHANTMENT_12_3", 57, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("ITEM_FIELD_PROPERTY_SEED", 58, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_RANDOM_PROPERTIES_ID", 59, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_DURABILITY", 60, 1, UpdateFieldType.Int, UpdateFieldFlag.Owner | UpdateFieldFlag.ItemOwner),
        new("ITEM_FIELD_MAXDURABILITY", 61, 1, UpdateFieldType.Int, UpdateFieldFlag.Owner | UpdateFieldFlag.ItemOwner),
        new("ITEM_FIELD_CREATE_PLAYED_TIME", 62, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("ITEM_FIELD_PAD", 63, 1, UpdateFieldType.Int, UpdateFieldFlag.None),
        new("CONTAINER_FIELD_NUM_SLOTS", 64, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("CONTAINER_ALIGN_PAD", 65, 1, UpdateFieldType.Bytes, UpdateFieldFlag.None),
        new("CONTAINER_FIELD_SLOT_1", 66, 72, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("UNIT_FIELD_CHARM", 6, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("UNIT_FIELD_SUMMON", 8, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("UNIT_FIELD_CRITTER", 10, 2, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("UNIT_FIELD_CHARMEDBY", 12, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("UNIT_FIELD_SUMMONEDBY", 14, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("UNIT_FIELD_CREATEDBY", 16, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("UNIT_FIELD_TARGET", 18, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("UNIT_FIELD_CHANNEL_OBJECT", 20, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("UNIT_CHANNEL_SPELL", 22, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_BYTES_0", 23, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("UNIT_FIELD_HEALTH", 24, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_POWER1", 25, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_POWER2", 26, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_POWER3", 27, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_POWER4", 28, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_POWER5", 29, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_POWER6", 30, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_POWER7", 31, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MAXHEALTH", 32, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MAXPOWER1", 33, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MAXPOWER2", 34, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MAXPOWER3", 35, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MAXPOWER4", 36, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MAXPOWER5", 37, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MAXPOWER6", 38, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MAXPOWER7", 39, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER", 40, 7, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER", 47, 7, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_LEVEL", 54, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_FACTIONTEMPLATE", 55, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_VIRTUAL_ITEM_SLOT_ID", 56, 3, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_FLAGS", 59, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_FLAGS_2", 60, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_AURASTATE", 61, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_BASEATTACKTIME", 62, 2, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_RANGEDATTACKTIME", 64, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("UNIT_FIELD_BOUNDINGRADIUS", 65, 1, UpdateFieldType.Float, UpdateFieldFlag.Public),
        new("UNIT_FIELD_COMBATREACH", 66, 1, UpdateFieldType.Float, UpdateFieldFlag.Public),
        new("UNIT_FIELD_DISPLAYID", 67, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_NATIVEDISPLAYID", 68, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MOUNTDISPLAYID", 69, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_MINDAMAGE", 70, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner | UpdateFieldFlag.PartyLeader),
        new("UNIT_FIELD_MAXDAMAGE", 71, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner | UpdateFieldFlag.PartyLeader),
        new("UNIT_FIELD_MINOFFHANDDAMAGE", 72, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner | UpdateFieldFlag.PartyLeader),
        new("UNIT_FIELD_MAXOFFHANDDAMAGE", 73, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner | UpdateFieldFlag.PartyLeader),
        new("UNIT_FIELD_BYTES_1", 74, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("UNIT_FIELD_PETNUMBER", 75, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_PET_NAME_TIMESTAMP", 76, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_PETEXPERIENCE", 77, 1, UpdateFieldType.Int, UpdateFieldFlag.Owner),
        new("UNIT_FIELD_PETNEXTLEVELEXP", 78, 1, UpdateFieldType.Int, UpdateFieldFlag.Owner),
        new("UNIT_DYNAMIC_FLAGS", 79, 1, UpdateFieldType.Int, UpdateFieldFlag.Dynamic),
        new("UNIT_MOD_CAST_SPEED", 80, 1, UpdateFieldType.Float, UpdateFieldFlag.Public),
        new("UNIT_CREATED_BY_SPELL", 81, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_NPC_FLAGS", 82, 1, UpdateFieldType.Int, UpdateFieldFlag.Dynamic),
        new("UNIT_NPC_EMOTESTATE", 83, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_STAT0", 84, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_STAT1", 85, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_STAT2", 86, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_STAT3", 87, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_STAT4", 88, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_POSSTAT0", 89, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_POSSTAT1", 90, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_POSSTAT2", 91, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_POSSTAT3", 92, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_POSSTAT4", 93, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_NEGSTAT0", 94, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_NEGSTAT1", 95, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_NEGSTAT2", 96, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_NEGSTAT3", 97, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_NEGSTAT4", 98, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_RESISTANCES", 99, 7, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner | UpdateFieldFlag.PartyLeader),
        new("UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE", 106, 7, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE", 113, 7, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_BASE_MANA", 120, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("UNIT_FIELD_BASE_HEALTH", 121, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_BYTES_2", 122, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("UNIT_FIELD_ATTACK_POWER", 123, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_ATTACK_POWER_MODS", 124, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_ATTACK_POWER_MULTIPLIER", 125, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_RANGED_ATTACK_POWER", 126, 1, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_RANGED_ATTACK_POWER_MODS", 127, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER", 128, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_MINRANGEDDAMAGE", 129, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_MAXRANGEDDAMAGE", 130, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_POWER_COST_MODIFIER", 131, 7, UpdateFieldType.Int, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_POWER_COST_MULTIPLIER", 138, 7, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_MAXHEALTHMODIFIER", 145, 1, UpdateFieldType.Float, UpdateFieldFlag.Private | UpdateFieldFlag.Owner),
        new("UNIT_FIELD_HOVERHEIGHT", 146, 1, UpdateFieldType.Float, UpdateFieldFlag.Public),
        new("UNIT_FIELD_PADDING", 147, 1, UpdateFieldType.Int, UpdateFieldFlag.None),
        new("PLAYER_DUEL_ARBITER", 148, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("PLAYER_FLAGS", 150, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_GUILDID", 151, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_GUILDRANK", 152, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_BYTES", 153, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("PLAYER_BYTES_2", 154, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("PLAYER_BYTES_3", 155, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("PLAYER_DUEL_TEAM", 156, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_GUILD_TIMESTAMP", 157, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_QUEST_LOG_1_1", 158, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_1_2", 159, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_1_3", 160, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_1_4", 162, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_2_1", 163, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_2_2", 164, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_2_3", 165, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_2_5", 167, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_3_1", 168, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_3_2", 169, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_3_3", 170, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_3_5", 172, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_4_1", 173, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_4_2", 174, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_4_3", 175, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_4_5", 177, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_5_1", 178, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_5_2", 179, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_5_3", 180, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_5_5", 182, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_6_1", 183, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_6_2", 184, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_6_3", 185, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_6_5", 187, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_7_1", 188, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_7_2", 189, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_7_3", 190, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_7_5", 192, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_8_1", 193, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_8_2", 194, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_8_3", 195, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_8_5", 197, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_9_1", 198, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_9_2", 199, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_9_3", 200, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_9_5", 202, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_10_1", 203, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_10_2", 204, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_10_3", 205, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_10_5", 207, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_11_1", 208, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_11_2", 209, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_11_3", 210, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_11_5", 212, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_12_1", 213, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_12_2", 214, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_12_3", 215, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_12_5", 217, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_13_1", 218, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_13_2", 219, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_13_3", 220, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_13_5", 222, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_14_1", 223, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_14_2", 224, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_14_3", 225, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_14_5", 227, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_15_1", 228, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_15_2", 229, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_15_3", 230, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_15_5", 232, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_16_1", 233, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_16_2", 234, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_16_3", 235, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_16_5", 237, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_17_1", 238, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_17_2", 239, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_17_3", 240, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_17_5", 242, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_18_1", 243, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_18_2", 244, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_18_3", 245, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_18_5", 247, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_19_1", 248, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_19_2", 249, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_19_3", 250, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_19_5", 252, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_20_1", 253, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_20_2", 254, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_20_3", 255, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_20_5", 257, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_21_1", 258, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_21_2", 259, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_21_3", 260, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_21_5", 262, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_22_1", 263, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_22_2", 264, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_22_3", 265, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_22_5", 267, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_23_1", 268, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_23_2", 269, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_23_3", 270, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_23_5", 272, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_24_1", 273, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_24_2", 274, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_24_3", 275, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_24_5", 277, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_25_1", 278, 1, UpdateFieldType.Int, UpdateFieldFlag.PartyMember),
        new("PLAYER_QUEST_LOG_25_2", 279, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_25_3", 280, 2, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_QUEST_LOG_25_5", 282, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_VISIBLE_ITEM_1_ENTRYID", 283, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_1_ENCHANTMENT", 284, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_2_ENTRYID", 285, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_2_ENCHANTMENT", 286, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_3_ENTRYID", 287, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_3_ENCHANTMENT", 288, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_4_ENTRYID", 289, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_4_ENCHANTMENT", 290, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_5_ENTRYID", 291, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_5_ENCHANTMENT", 292, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_6_ENTRYID", 293, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_6_ENCHANTMENT", 294, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_7_ENTRYID", 295, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_7_ENCHANTMENT", 296, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_8_ENTRYID", 297, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_8_ENCHANTMENT", 298, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_9_ENTRYID", 299, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_9_ENCHANTMENT", 300, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_10_ENTRYID", 301, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_10_ENCHANTMENT", 302, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_11_ENTRYID", 303, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_11_ENCHANTMENT", 304, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_12_ENTRYID", 305, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_12_ENCHANTMENT", 306, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_13_ENTRYID", 307, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_13_ENCHANTMENT", 308, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_14_ENTRYID", 309, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_14_ENCHANTMENT", 310, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_15_ENTRYID", 311, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_15_ENCHANTMENT", 312, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_16_ENTRYID", 313, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_16_ENCHANTMENT", 314, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_17_ENTRYID", 315, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_17_ENCHANTMENT", 316, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_18_ENTRYID", 317, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_18_ENCHANTMENT", 318, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_19_ENTRYID", 319, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_VISIBLE_ITEM_19_ENCHANTMENT", 320, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Public),
        new("PLAYER_CHOSEN_TITLE", 321, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_FAKE_INEBRIATION", 322, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("PLAYER_FIELD_PAD_0", 323, 1, UpdateFieldType.Int, UpdateFieldFlag.None),
        new("PLAYER_FIELD_INV_SLOT_HEAD", 324, 46, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_PACK_SLOT_1", 370, 32, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_BANK_SLOT_1", 402, 56, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_BANKBAG_SLOT_1", 458, 14, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_VENDORBUYBACK_SLOT_1", 472, 24, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_KEYRING_SLOT_1", 496, 64, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_CURRENCYTOKEN_SLOT_1", 560, 64, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_FARSIGHT", 624, 2, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER__FIELD_KNOWN_TITLES", 626, 2, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER__FIELD_KNOWN_TITLES1", 628, 2, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER__FIELD_KNOWN_TITLES2", 630, 2, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_KNOWN_CURRENCIES", 632, 2, UpdateFieldType.Long, UpdateFieldFlag.Private),
        new("PLAYER_XP", 634, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_NEXT_LEVEL_XP", 635, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_SKILL_INFO_1_1", 636, 384, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_CHARACTER_POINTS1", 1020, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_CHARACTER_POINTS2", 1021, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_TRACK_CREATURES", 1022, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_TRACK_RESOURCES", 1023, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_BLOCK_PERCENTAGE", 1024, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_DODGE_PERCENTAGE", 1025, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_PARRY_PERCENTAGE", 1026, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_EXPERTISE", 1027, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_OFFHAND_EXPERTISE", 1028, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_CRIT_PERCENTAGE", 1029, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_RANGED_CRIT_PERCENTAGE", 1030, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_OFFHAND_CRIT_PERCENTAGE", 1031, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_SPELL_CRIT_PERCENTAGE1", 1032, 7, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_SHIELD_BLOCK", 1039, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE", 1040, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_EXPLORED_ZONES_1", 1041, 128, UpdateFieldType.Bytes, UpdateFieldFlag.Private),
        new("PLAYER_REST_STATE_EXPERIENCE", 1169, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_COINAGE", 1170, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MOD_DAMAGE_DONE_POS", 1171, 7, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MOD_DAMAGE_DONE_NEG", 1178, 7, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MOD_DAMAGE_DONE_PCT", 1185, 7, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MOD_HEALING_DONE_POS", 1192, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MOD_HEALING_PCT", 1193, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MOD_HEALING_DONE_PCT", 1194, 1, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MOD_TARGET_RESISTANCE", 1195, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE", 1196, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_BYTES", 1197, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Private),
        new("PLAYER_AMMO_ID", 1198, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_SELF_RES_SPELL", 1199, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_PVP_MEDALS", 1200, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_BUYBACK_PRICE_1", 1201, 12, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_BUYBACK_TIMESTAMP_1", 1213, 12, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_KILLS", 1225, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_TODAY_CONTRIBUTION", 1226, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_YESTERDAY_CONTRIBUTION", 1227, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_LIFETIME_HONORABLE_KILLS", 1228, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_WATCHED_FACTION_INDEX", 1230, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_COMBAT_RATING_1", 1231, 25, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_ARENA_TEAM_INFO_1_1", 1256, 21, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_HONOR_CURRENCY", 1277, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_ARENA_CURRENCY", 1278, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_MAX_LEVEL", 1279, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_DAILY_QUESTS_1", 1280, 25, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_RUNE_REGEN_1", 1305, 4, UpdateFieldType.Float, UpdateFieldFlag.Private),
        new("PLAYER_NO_REAGENT_COST_1", 1309, 3, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_GLYPH_SLOTS_1", 1312, 6, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_FIELD_GLYPHS_1", 1318, 6, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_GLYPHS_ENABLED", 1324, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("PLAYER_PET_SPELL_POWER", 1325, 1, UpdateFieldType.Int, UpdateFieldFlag.Private),
        new("OBJECT_FIELD_CREATED_BY", 6, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("GAMEOBJECT_DISPLAYID", 8, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("GAMEOBJECT_FLAGS", 9, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("GAMEOBJECT_PARENTROTATION", 10, 4, UpdateFieldType.Float, UpdateFieldFlag.Public),
        new("GAMEOBJECT_DYNAMIC", 14, 1, UpdateFieldType.TwoShort, UpdateFieldFlag.Dynamic),
        new("GAMEOBJECT_FACTION", 15, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("GAMEOBJECT_LEVEL", 16, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("GAMEOBJECT_BYTES_1", 17, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("DYNAMICOBJECT_CASTER", 6, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("DYNAMICOBJECT_BYTES", 8, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("DYNAMICOBJECT_SPELLID", 9, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("DYNAMICOBJECT_RADIUS", 10, 1, UpdateFieldType.Float, UpdateFieldFlag.Public),
        new("DYNAMICOBJECT_CASTTIME", 11, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_OWNER", 6, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_PARTY", 8, 2, UpdateFieldType.Long, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_DISPLAY_ID", 10, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_ITEM", 11, 19, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_BYTES_1", 30, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_BYTES_2", 31, 1, UpdateFieldType.Bytes, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_GUILD", 32, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_FLAGS", 33, 1, UpdateFieldType.Int, UpdateFieldFlag.Public),
        new("CORPSE_FIELD_DYNAMIC_FLAGS", 34, 1, UpdateFieldType.Int, UpdateFieldFlag.Dynamic),
        new("CORPSE_FIELD_PAD", 35, 1, UpdateFieldType.Int, UpdateFieldFlag.None),
    ];

    /// <summary>Every named field, with its size, type and visibility.</summary>
    public static IReadOnlyList<UpdateFieldInfo> All => AllFields;

    /// <summary>Looks up a field's metadata by index. Null for indices no name covers.</summary>
    public static UpdateFieldInfo? Find(int index)
    {
        foreach (UpdateFieldInfo field in AllFields)
        {
            if (field.Index == index)
            {
                return field;
            }
        }

        return null;
    }
}
