#!/usr/bin/env python3
"""Generates src/WowEmu.Protocol/OpcodeTable.g.cs from AzerothCore's Opcodes.cpp.

PLAN.md section 4.2 rule 4: the per-opcode SessionStatus / PacketProcessing classification is
"kept verbatim -- it is the contract that makes rule 1 hold". There is not a single mutex in the
C++ entities, spells, combat, movement or AI code; this table is the *entire* thread-safety story.
A hand-copied entry that says THREADSAFE where upstream says THREADUNSAFE would put a packet on a
map worker that upstream only ever runs on the world thread, and the resulting corruption would be
rare, timing-dependent and effectively undebuggable.

So it is generated, and re-running this after an upstream change produces a reviewable diff.

The upstream handler name is carried along too: when a later phase implements an opcode, that name
is where to look in the C++ for the behaviour being ported.

    python3 tools/codegen/generate_opcode_table.py
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SOURCE = os.path.join(ROOT, "azerothcore-wotlk", "src", "server", "game", "Server", "Protocol", "Opcodes.cpp")
OUTPUT = os.path.join(ROOT, "src", "WowEmu.Protocol", "OpcodeTable.g.cs")

CLIENT = re.compile(
    r"DEFINE_HANDLER\(\s*([A-Z_0-9]+)\s*,\s*(STATUS_[A-Z_]+)\s*,\s*(PROCESS_[A-Z_]+)\s*,"
    r"\s*&WorldSession::([A-Za-z_0-9]+)\s*\)")
SERVER = re.compile(r"DEFINE_SERVER_OPCODE_HANDLER\(\s*([A-Z_0-9]+)\s*,\s*(STATUS_[A-Z_]+)\s*\)")

STATUS = {
    "STATUS_AUTHED": "Authed",
    "STATUS_LOGGEDIN": "LoggedIn",
    "STATUS_TRANSFER": "Transfer",
    "STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT": "LoggedInOrRecentlyLoggedOut",
    "STATUS_NEVER": "Never",
    "STATUS_UNHANDLED": "Unhandled",
}

PROCESSING = {
    "PROCESS_INPLACE": "Inplace",
    "PROCESS_THREADUNSAFE": "ThreadUnsafe",
    "PROCESS_THREADSAFE": "ThreadSafe",
}

HEADER = '''// <auto-generated>
//     Generated by tools/codegen/generate_opcode_table.py from AzerothCore's Opcodes.cpp.
//     Do not edit by hand -- regenerate instead.
// </auto-generated>

// A file the compiler treats as generated opts out of the project's nullable context, so it has to
// be turned back on explicitly -- the table's UpstreamHandler is deliberately nullable.
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace WowEmu.Protocol;

/// <summary>How far through login a session must be for an opcode to be legal.</summary>
public enum SessionStatus : byte
{
    /// <summary>Authenticated, but with no player in the world yet.</summary>
    Authed = 0,

    /// <summary>Player is in the world.</summary>
    LoggedIn,

    /// <summary>Player is moving between maps.</summary>
    Transfer,

    /// <summary>Player is in the world, or logged out so recently that the session still knows them.</summary>
    LoggedInOrRecentlyLoggedOut,

    /// <summary>Never accepted from a client: server-side only, or deprecated.</summary>
    Never,

    /// <summary>Upstream has no handler for this yet either.</summary>
    Unhandled,
}

/// <summary>
/// Which loop may run an opcode's handler.
/// </summary>
/// <remarks>
/// This classification is the whole of the threading contract described in PLAN.md section 4.2.
/// It is transcribed from upstream unchanged and must stay that way: a handler upstream marks
/// <see cref="ThreadUnsafe"/> touches state that only the world tick may touch, and running it on
/// a map worker instead would corrupt that state in a way that reproduces once a week.
/// </remarks>
public enum PacketProcessing : byte
{
    /// <summary>Run as soon as it arrives — unhandled or trivial packets.</summary>
    Inplace = 0,

    /// <summary>Must run on the world tick.</summary>
    ThreadUnsafe,

    /// <summary>May run on the owning map's worker.</summary>
    ThreadSafe,
}

/// <summary>What the opcode table knows about one opcode.</summary>
/// <param name="Opcode">The opcode itself.</param>
/// <param name="Status">Session state required before a client may send it.</param>
/// <param name="Processing">Which loop may run the handler.</param>
/// <param name="UpstreamHandler">
/// Name of AzerothCore's handler, or <c>null</c> for a server-to-client opcode. This is the place
/// to look in the C++ when the time comes to port the behaviour.
/// </param>
public readonly record struct OpcodeInfo(
    Opcode Opcode,
    SessionStatus Status,
    PacketProcessing Processing,
    string? UpstreamHandler)
{
    /// <summary>True for opcodes the server only ever sends.</summary>
    public bool IsServerOpcode => UpstreamHandler is null;

    /// <summary>Whether a client may legally send this at all.</summary>
    public bool IsClientSendable => Status is not (SessionStatus.Never or SessionStatus.Unhandled);
}

/// <summary>
/// The complete opcode table: every opcode's required session status and processing class.
/// </summary>
/// <remarks>
/// Generated from upstream, so it covers opcodes no phase has implemented yet. Knowing that an
/// unimplemented opcode is <see cref="SessionStatus.Never"/> is what lets the session reject junk
/// instead of guessing.
/// </remarks>
public static class OpcodeTable
{
    private static readonly OpcodeInfo[] Entries =
    [
'''

FOOTER = '''    ];

    private static readonly OpcodeInfo?[] ByValue = BuildIndex();

    /// <summary>Every classified opcode.</summary>
    public static IReadOnlyList<OpcodeInfo> All => Entries;

    /// <summary>Looks up an opcode. False means upstream does not classify it at all.</summary>
    public static bool TryGet(Opcode opcode, [NotNullWhen(true)] out OpcodeInfo? info)
    {
        ushort value = (ushort)opcode;

        info = value < ByValue.Length ? ByValue[value] : null;
        return info is not null;
    }

    /// <summary>
    /// Whether a client may send this opcode while the session is in <paramref name="status"/>.
    /// </summary>
    /// <remarks>
    /// An unknown opcode is refused. Upstream reaches the same outcome by bounds-checking against
    /// the handler array, which is the same rule expressed as an array index.
    /// </remarks>
    public static bool IsAllowedFrom(Opcode opcode, SessionStatus status)
    {
        if (!TryGet(opcode, out OpcodeInfo? info) || !info.Value.IsClientSendable)
        {
            return false;
        }

        return info.Value.Status switch
        {
            SessionStatus.Authed => true,
            SessionStatus.LoggedIn or SessionStatus.Transfer or SessionStatus.LoggedInOrRecentlyLoggedOut
                => status is SessionStatus.LoggedIn or SessionStatus.Transfer
                    or SessionStatus.LoggedInOrRecentlyLoggedOut,
            _ => false,
        };
    }

    private static OpcodeInfo?[] BuildIndex()
    {
        ushort highest = 0;
        foreach (OpcodeInfo entry in Entries)
        {
            highest = Math.Max(highest, (ushort)entry.Opcode);
        }

        OpcodeInfo?[] index = new OpcodeInfo?[highest + 1];
        foreach (OpcodeInfo entry in Entries)
        {
            index[(ushort)entry.Opcode] = entry;
        }

        return index;
    }
}
'''


def main():
    if not os.path.exists(SOURCE):
        print(f"error: {SOURCE} not found -- is azerothcore-wotlk/ present?")
        return 1

    entries = []
    seen = set()
    duplicates = []

    with open(SOURCE) as handle:
        for line in handle:
            client = CLIENT.search(line)
            server = SERVER.search(line)

            if client:
                name, status, processing, handler = client.groups()
                record = (name, STATUS[status], PROCESSING[processing], f'"{handler}"')
            elif server:
                name, status = server.groups()
                record = (name, STATUS[status], "Inplace", "null")
            else:
                continue

            if name in seen:
                duplicates.append(name)
                continue

            seen.add(name)
            entries.append(record)

    if not entries:
        print("error: no handlers parsed -- did the macro format change?")
        return 1

    with open(OUTPUT, "w") as handle:
        handle.write(HEADER)
        for name, status, processing, upstream in entries:
            handle.write(
                f"        new(Opcode.{name}, SessionStatus.{status}, "
                f"PacketProcessing.{processing}, {upstream}),\n")
        handle.write(FOOTER)

    clients = sum(1 for entry in entries if entry[3] != "null")
    print(f"wrote {OUTPUT}: {len(entries)} opcodes ({clients} client handlers, {len(entries) - clients} server-only)")

    if duplicates:
        print(f"note: skipped {len(duplicates)} repeated name(s): {', '.join(duplicates[:5])}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
