#!/usr/bin/env python3
"""Generates src/WowEmu.Protocol/UpdateFields.g.cs from AzerothCore's UpdateFields.h.

Update fields are the flat uint32 array that carries every visible property of every object to the
client. There are 381 named indices and the layout is the client's, not ours -- PLAYER_END is 1326
because that is where the 3.3.5a client stops reading.

Three reasons this is generated rather than typed:

1. The values are *cumulative*. PLAYER_* indices are expressed as UNIT_END + offset, and UNIT_END
   is OBJECT_END + offset. One wrong base shifts a hundred fields at once.
2. Each field carries a size, a type and visibility flags in a trailing comment. Those flags decide
   which observers may see a field -- get PRIVATE wrong and you leak another player's inventory, or
   hide a field the owner needs.
3. A wrong index is not an error. It writes a valid uint32 to the wrong slot, and the client renders
   something subtly wrong somewhere else entirely.

    python3 tools/codegen/generate_update_fields.py
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SOURCE = os.path.join(
    ROOT, "azerothcore-wotlk", "src", "server", "game", "Entities", "Object", "Updates", "UpdateFields.h")
OUTPUT = os.path.join(ROOT, "src", "WowEmu.Protocol", "UpdateFields.g.cs")

ENUM = re.compile(r"^enum\s+(E\w+)")
# NAME = 0x1234,  |  NAME = OTHER_NAME + 0x1234,   with an optional trailing metadata comment.
ENTRY = re.compile(
    r"^\s+([A-Z][A-Z_0-9]*)\s*=\s*(?:([A-Z][A-Z_0-9]*)\s*\+\s*)?0x([0-9A-Fa-f]+)\s*,?"
    r"(?:\s*//\s*Size:\s*(\d+),\s*Type:\s*([A-Z_]+),\s*Flags:\s*([A-Z_, ]+))?")

# Upstream's visibility flags, as a [Flags] enum. Values are ours -- upstream expresses them as a
# separate UpdateFieldFlags enum with the same meanings.
FLAGS = {
    "NONE": "None",
    "PUBLIC": "Public",
    "PRIVATE": "Private",
    "OWNER": "Owner",
    "ITEM_OWNER": "ItemOwner",
    "PARTY_MEMBER": "PartyMember",
    "PARTY_LEADER": "PartyLeader",
    "DYNAMIC": "Dynamic",
    "UNUSED": "None",
}

TYPES = {
    "INT": "Int",
    "LONG": "Long",
    "FLOAT": "Float",
    "BYTES": "Bytes",
    "TWO_SHORT": "TwoShort",
}

HEADER = '''// <auto-generated>
//     Generated by tools/codegen/generate_update_fields.py from AzerothCore's UpdateFields.h.
//     Do not edit by hand -- regenerate instead.
// </auto-generated>

#nullable enable

namespace WowEmu.Protocol;

/// <summary>
/// How wide a field is and how the client interprets it.
/// </summary>
/// <remarks>
/// <see cref="Long"/> and <see cref="Bytes"/> are the ones that catch people: a LONG occupies two
/// consecutive uint32 slots, and BYTES is four independent bytes packed into one slot, so neither
/// can be written with a plain 32-bit assignment.
/// </remarks>
public enum UpdateFieldType : byte
{
    Int = 0,
    Long,
    Float,
    Bytes,
    TwoShort,
}

/// <summary>
/// Who is allowed to see a field.
/// </summary>
/// <remarks>
/// This is not decoration. The same object is serialized differently per observer: a player sees
/// their own <see cref="Private"/> fields, party members see <see cref="PartyMember"/> ones, and
/// everybody sees <see cref="Public"/>. Treating a private field as public leaks another player's
/// state to everyone nearby.
/// </remarks>
[Flags]
public enum UpdateFieldFlag : byte
{
    None = 0x00,
    Public = 0x01,
    Private = 0x02,
    Owner = 0x04,
    ItemOwner = 0x08,
    PartyMember = 0x10,
    PartyLeader = 0x20,
    Dynamic = 0x40,
}

/// <summary>Metadata for one update field.</summary>
public readonly record struct UpdateFieldInfo(
    string Name,
    int Index,
    int Size,
    UpdateFieldType Type,
    UpdateFieldFlag Flags);

/// <summary>
/// Update-field indices, transcribed from the 3.3.5a client's layout.
/// </summary>
/// <remarks>
/// Indices are into a flat <c>uint[]</c>. They are cumulative across the object hierarchy: unit
/// fields start where object fields end, player fields where unit fields end. The <c>*_END</c>
/// values are therefore both the end of one block and the base of the next.
/// </remarks>
public static class UpdateFields
{
'''

FOOTER = '''
    private static readonly UpdateFieldInfo[] AllFields =
    [
%ENTRIES%
    ];

    /// <summary>Every named field, with its size, type and visibility.</summary>
    public static IReadOnlyList<UpdateFieldInfo> All => AllFields;

    /// <summary>Looks up a field's metadata by index. Null for indices no name covers.</summary>
    public static UpdateFieldInfo? Find(int index)
    {
        foreach (UpdateFieldInfo field in AllFields)
        {
            if (field.Index == index)
            {
                return field;
            }
        }

        return null;
    }
}
'''


def parse():
    constants = {}
    order = []
    metadata = []
    current_enum = None

    with open(SOURCE) as handle:
        for line in handle:
            enum_match = ENUM.match(line)
            if enum_match:
                current_enum = enum_match.group(1)
                continue

            if current_enum is None:
                continue

            if line.startswith("}"):
                current_enum = None
                continue

            entry = ENTRY.match(line)
            if not entry:
                continue

            name, base, offset, size, type_name, flag_names = entry.groups()

            value = int(offset, 16)
            if base:
                if base not in constants:
                    raise SystemExit(f"error: {name} refers to {base} before it is defined")
                value += constants[base]

            if name in constants:
                continue

            constants[name] = value
            order.append((name, value))

            if size and type_name:
                flags = [FLAGS[f.strip()] for f in flag_names.split(",") if f.strip() in FLAGS]
                flags = [f for f in flags if f != "None"] or ["None"]
                metadata.append((name, value, int(size), TYPES[type_name], " | ".join(
                    f"UpdateFieldFlag.{f}" for f in dict.fromkeys(flags))))

    return order, metadata


def main():
    if not os.path.exists(SOURCE):
        print(f"error: {SOURCE} not found -- is azerothcore-wotlk/ present?")
        return 1

    order, metadata = parse()

    if not order:
        print("error: no fields parsed -- did the header format change?")
        return 1

    lines = []
    for name, value in order:
        lines.append(f"    /// <summary>Index {value}.</summary>\n    public const int {name} = {value};\n")

    entries = "\n".join(
        f'        new("{name}", {value}, {size}, UpdateFieldType.{type_name}, {flags}),'
        for name, value, size, type_name, flags in metadata)

    with open(OUTPUT, "w") as handle:
        handle.write(HEADER)
        handle.write("\n".join(lines))
        handle.write(FOOTER.replace("%ENTRIES%", entries))

    print(f"wrote {OUTPUT}: {len(order)} constants, {len(metadata)} with metadata")
    for key in ("OBJECT_END", "ITEM_END", "CONTAINER_END", "UNIT_END", "PLAYER_END",
                "GAMEOBJECT_END", "DYNAMICOBJECT_END", "CORPSE_END"):
        value = dict(order).get(key)
        print(f"  {key:<20} {value}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
