#!/usr/bin/env python3
"""Generates src/WowEmu.Protocol/Opcodes.g.cs from AzerothCore's Opcodes.h.

There are ~1300 opcodes. Hand-transcribing them would be a thousand chances to fat-finger a hex
digit into a value that is still a *valid* opcode -- the packet would go to the wrong handler with
no error anywhere. Generating them removes that entire class of bug, and re-running this after an
upstream update produces a reviewable diff instead of a silent drift.

Names are kept exactly as upstream spells them, including the ones that are misspelled or
inconsistent. They are the shared vocabulary between this project and every wiki page, forum post
and packet capture about 3.3.5a; "fixing" them would cost more than it buys.

    python3 tools/codegen/generate_opcodes.py
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SOURCE = os.path.join(ROOT, "azerothcore-wotlk", "src", "server", "game", "Server", "Protocol", "Opcodes.h")
OUTPUT = os.path.join(ROOT, "src", "WowEmu.Protocol", "Opcodes.g.cs")

OPCODE = re.compile(r"^\s+([A-Z][A-Z_0-9]*)\s*=\s*(0x[0-9A-Fa-f]+)\s*,?\s*(?://.*)?$")

HEADER = """// <auto-generated>
//     Generated by tools/codegen/generate_opcodes.py from AzerothCore's Opcodes.h.
//     Do not edit by hand -- regenerate instead.
// </auto-generated>

namespace WowEmu.Protocol;

/// <summary>
/// Every opcode the 3.3.5a client and server exchange.
/// </summary>
/// <remarks>
/// Transcribed mechanically from <c>src/server/game/Server/Protocol/Opcodes.h</c>. Names are
/// upstream's, verbatim -- they are the shared vocabulary of every 3.3.5a packet capture and wiki
/// page, so they are worth more unchanged than tidied.
/// <para>
/// The opcode occupies a <see cref="ushort"/> on the wire even though the client header reserves
/// four bytes for it.
/// </para>
/// </remarks>
public enum Opcode : ushort
{
"""

FOOTER = """}
"""


def main():
    if not os.path.exists(SOURCE):
        print(f"error: {SOURCE} not found -- is azerothcore-wotlk/ present?")
        return 1

    seen = {}
    entries = []
    duplicates = []

    with open(SOURCE) as handle:
        inside = False
        for line in handle:
            stripped = line.strip()

            if stripped.startswith("enum Opcodes"):
                inside = True
                continue

            if inside and stripped.startswith("}"):
                break

            if not inside:
                continue

            match = OPCODE.match(line.rstrip("\n"))
            if not match:
                continue

            name, value = match.group(1), match.group(2).upper().replace("0X", "0x")
            numeric = int(value, 16)

            # C# enums reject duplicate *names*, but duplicate values are legal and do occur --
            # keep the first spelling and record the alias as a comment so nothing is lost.
            if name in seen:
                continue

            if numeric in seen.values():
                duplicates.append((name, numeric))

            seen[name] = numeric
            entries.append((name, value))

    if not entries:
        print("error: no opcodes parsed -- did the header format change?")
        return 1

    with open(OUTPUT, "w") as handle:
        handle.write(HEADER)
        for name, value in entries:
            handle.write(f"    {name} = {value},\n")
        handle.write(FOOTER)

    print(f"wrote {OUTPUT}: {len(entries)} opcodes")
    if duplicates:
        print(f"note: {len(duplicates)} share a value with an earlier opcode (legal, kept)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
