#!/usr/bin/env python3
"""Generates src/WowEmu.Protocol/UpdateFieldFlags.g.cs from AzerothCore's UpdateFieldFlags.cpp.

The same object is serialized differently for different observers. A player sees their own private
fields; a party member sees some of them; a stranger sees only the public ones. Upstream decides
that per *index*, from five dense arrays -- one per object type -- and that is what this generates.

Why the arrays and not the `Flags:` comments in UpdateFields.h:

1. They are dense. Every index has an entry, including the padding and the unnamed slots inside a
   multi-word field. UpdateFields.h names 372 fields; PLAYER_END is 1326, and the ~950 unnamed
   indices in between still need a visibility, because a mask bit can be set on any of them.
2. Index alone does not identify a field. The blocks are relative to their own hierarchy base, so
   index 8 is DYNAMICOBJECT_BYTES *and* CORPSE_FIELD_PARTY. Only the per-type array disambiguates.
3. UpdateFieldFlags.cpp is what upstream's BuildValuesUpdate actually reads. The header comments are
   documentation, and they disagree in places -- they name a PARTY_LEADER flag the runtime does not
   have, and omit SPECIAL_INFO, which it does.

    python3 tools/codegen/generate_update_field_flags.py
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SOURCE = os.path.join(
    ROOT, "azerothcore-wotlk", "src", "server", "game", "Entities", "Object", "Updates",
    "UpdateFieldFlags.cpp")
OUTPUT = os.path.join(ROOT, "src", "WowEmu.Protocol", "UpdateFieldFlags.g.cs")

ARRAY = re.compile(r"^uint32\s+(\w+)UpdateFieldFlags\[(\w+)\]\s*=")
ENTRY = re.compile(r"^\s*(UF_FLAG_[A-Z_0-9]+(?:\s*\|\s*UF_FLAG_[A-Z_0-9]+)*)\s*,")

# Upstream's own values, verbatim. Not the ones in UpdateFields.h's comments -- see the docstring.
FLAG_VALUES = {
    "UF_FLAG_NONE": 0x000,
    "UF_FLAG_PUBLIC": 0x001,
    "UF_FLAG_PRIVATE": 0x002,
    "UF_FLAG_OWNER": 0x004,
    "UF_FLAG_UNUSED1": 0x008,
    "UF_FLAG_ITEM_OWNER": 0x010,
    "UF_FLAG_SPECIAL_INFO": 0x020,
    "UF_FLAG_PARTY_MEMBER": 0x040,
    "UF_FLAG_UNUSED2": 0x080,
    "UF_FLAG_DYNAMIC": 0x100,
}

# What each array is called on our side, and the doc comment it gets.
NAMES = {
    "Item": ("Item", "Items and containers. CONTAINER_END covers both; an item is a prefix of a bag."),
    "Unit": ("Unit", "Creatures and players. PLAYER_END covers both; a creature is a prefix of a player."),
    "GameObject": ("GameObject", "Gameobjects: doors, chests, quest props."),
    "DynamicObject": ("DynamicObject", "Dynamic objects: persistent ground-targeted spell areas."),
    "Corpse": ("Corpse", "A dead player's body, as a world object in its own right."),
}

HEADER = '''// <auto-generated>
//     Generated by tools/codegen/generate_update_field_flags.py from AzerothCore's
//     UpdateFieldFlags.cpp. Do not edit by hand -- rerun the generator.
// </auto-generated>

namespace WowEmu.Protocol;

/// <summary>
/// Which observers may see a given update field.
/// </summary>
/// <remarks>
/// <para>
/// Upstream's <c>UpdatefieldFlags</c>, with upstream's values. These are not the flags spelled out
/// in the <c>Flags:</c> comments of <c>UpdateFields.h</c> -- those are documentation, they disagree
/// with the runtime table in places, and it is the runtime table that decides what goes on the wire.
/// </para>
/// <para>
/// <see cref="Unused1"/> and <see cref="Unused2"/> are kept so the bit values line up with
/// upstream's. Renumbering to close the gaps would make every value here silently different from the
/// one it was copied from.
/// </para>
/// </remarks>
[System.Flags]
public enum UpdateFieldVisibility
{
    None = 0x000,

    /// <summary>Everyone who can see the object at all.</summary>
    Public = 0x001,

    /// <summary>The object itself, when it is a player looking at its own fields.</summary>
    Private = 0x002,

    /// <summary>Whoever owns the object -- a pet's master, an item's holder.</summary>
    Owner = 0x004,

    Unused1 = 0x008,

    /// <summary>The owner of the item, as distinct from the owner of the container.</summary>
    ItemOwner = 0x010,

    /// <summary>
    /// Visible to someone who has targeted the object with a detect-type effect.
    /// </summary>
    /// <remarks>
    /// Upstream gates this on the observer having the object in its <c>m_targetIcon</c>-style
    /// special-info set, which we have no equivalent of yet. Treated as not visible.
    /// </remarks>
    SpecialInfo = 0x020,

    /// <summary>Members of the object's party.</summary>
    PartyMember = 0x040,

    Unused2 = 0x080,

    /// <summary>
    /// Fields whose value depends on who is asking.
    /// </summary>
    /// <remarks>
    /// Upstream rewrites these per observer rather than filtering them -- the lootable flag on a
    /// corpse is the standard example, since it is true only for whoever may loot it. We do not
    /// rewrite them yet, so they are sent as stored.
    /// </remarks>
    Dynamic = 0x100,
}

/// <summary>
/// Per-index visibility, one dense array per object type.
/// </summary>
/// <remarks>
/// Indexed by update-field index. Dense rather than keyed by name because a mask bit can be set on
/// any index, including the unnamed ones inside a multi-word field, and because the same index means
/// different things in different object types.
/// </remarks>
public static class UpdateFieldFlags
{
'''

FOOTER = '''}
'''


def parse():
    """Returns [(array name, end constant, [flag expressions])] in file order."""
    arrays = []
    current = None

    with open(SOURCE) as handle:
        for line in handle:
            match = ARRAY.match(line)

            if match:
                current = (match.group(1), match.group(2), [])
                arrays.append(current)
                continue

            if current is None:
                continue

            if line.startswith("};"):
                current = None
                continue

            entry = ENTRY.match(line)

            if entry:
                current[2].append(entry.group(1))

    return arrays


def value_of(expression):
    """Turns `UF_FLAG_OWNER | UF_FLAG_ITEM_OWNER` into an int."""
    total = 0

    for part in expression.split("|"):
        name = part.strip()

        if name not in FLAG_VALUES:
            raise SystemExit(f"error: unknown flag {name!r}")

        total |= FLAG_VALUES[name]

    return total


def emit(name, end_constant, values):
    label, description = NAMES[name]

    lines = [
        f"    /// <summary>{description}</summary>",
        f"    /// <remarks>{len(values)} entries, matching upstream's {end_constant}.</remarks>",
        f"    public static ReadOnlySpan<ushort> {label} =>",
        "    [",
    ]

    # Sixteen per line: wide enough not to be a thousand-line file, narrow enough to diff.
    for start in range(0, len(values), 16):
        row = ", ".join(f"0x{value:03X}" for value in values[start:start + 16])
        lines.append(f"        {row},")

    lines.append("    ];")
    return "\n".join(lines)


def main():
    if not os.path.exists(SOURCE):
        print(f"error: {SOURCE} not found -- is azerothcore-wotlk/ present?", file=sys.stderr)
        return 1

    arrays = parse()

    if len(arrays) != len(NAMES):
        print(f"error: expected {len(NAMES)} arrays, found {len(arrays)}", file=sys.stderr)
        return 1

    blocks = []
    summary = []

    for name, end_constant, expressions in arrays:
        if name not in NAMES:
            print(f"error: unexpected array {name!r}", file=sys.stderr)
            return 1

        values = [value_of(expression) for expression in expressions]

        if any(value > 0xFFFF for value in values):
            print("error: a flag value does not fit in ushort", file=sys.stderr)
            return 1

        blocks.append(emit(name, end_constant, values))
        summary.append(f"{NAMES[name][0]}={len(values)}")

    with open(OUTPUT, "w") as handle:
        handle.write(HEADER)
        handle.write("\n\n".join(blocks))
        handle.write("\n")
        handle.write(FOOTER)

    print(f"wrote {OUTPUT}: {', '.join(summary)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
