/*
 * Golden SFMT-19937 vectors, generated by the *original C implementation*.
 *
 * This compiles AzerothCore's vendored deps/SFMT/SFMT.c — the same code the C++ server runs — and
 * dumps its output as JSON. Asserting our C# port against these is the only check that actually
 * proves the two bit streams agree; a C#-vs-C# test would prove nothing about the port.
 *
 * Build and run via tools/vectors/generate_sfmt_vectors.sh. The scalar path is forced (no SSE2,
 * NEON or AltiVec) because that is what the C# port transcribes; all three paths produce identical
 * output by construction, so this is a fair reference either way.
 */
#include <stdio.h>
#include <stdint.h>
#include "SFMT.h"

#define DRAWS 16
#define SKIP_TO 10000

static void dump_draws(sfmt_t *sfmt, const char *name, int trailing_comma)
{
    printf("  \"%s\": [", name);
    for (int i = 0; i < DRAWS; i++)
    {
        printf("%s%u", i ? ", " : "", sfmt_genrand_uint32(sfmt));
    }
    printf("]%s\n", trailing_comma ? "," : "");
}

int main(void)
{
    sfmt_t sfmt;
    uint32_t key[] = {0x1234, 0x5678, 0x9ABC, 0xDEF0};

    printf("{\n");
    printf("  \"_comment\": \"Generated by tools/vectors/generate_sfmt_vectors.c from AzerothCore deps/SFMT. Do not hand-edit.\",\n");
    printf("  \"mexp\": %d,\n", SFMT_MEXP);
    printf("  \"n32\": %d,\n", SFMT_N32);

    /* init_gen_rand with a single scalar seed. */
    sfmt_init_gen_rand(&sfmt, 42);
    dump_draws(&sfmt, "init_gen_rand_42", 1);

    sfmt_init_gen_rand(&sfmt, 0);
    dump_draws(&sfmt, "init_gen_rand_0", 1);

    /* init_by_array — the path SFMTRand uses, and the one PLAN.md names as the exit criterion. */
    sfmt_init_by_array(&sfmt, key, 4);
    dump_draws(&sfmt, "init_by_array_1234_5678_9abc_def0", 1);

    /* Cross a state regeneration boundary: N32 is 624, so this exercises gen_rand_all repeatedly. */
    sfmt_init_gen_rand(&sfmt, 42);
    for (int i = 0; i < SKIP_TO; i++)
    {
        (void)sfmt_genrand_uint32(&sfmt);
    }
    dump_draws(&sfmt, "init_gen_rand_42_after_10000", 0);

    printf("}\n");
    return 0;
}
