/*
 * Golden vectors for the game's random distributions: urand, irand, frand and rand_norm.
 *
 * These are the *distributions*, not the generator. AzerothCore does not roll its own — it feeds
 * SFMT into libstdc++'s std::uniform_int_distribution and std::uniform_real_distribution. Those
 * have specific algorithms: the integer one rejection-samples and therefore consumes a variable
 * number of 32-bit draws per call, and the real one consumes one draw for float and two for double.
 * Any reimplementation that gets the draw count wrong will desynchronise the two servers' streams
 * after the very first roll, which is exactly what differential testing needs to not happen.
 *
 * So this links the real SFMT against the real libstdc++ and records what comes out.
 *
 * Must be built against libstdc++ — libc++ (the macOS default) implements uniform_int_distribution
 * differently and would produce a confidently wrong answer. tools/vectors/generate_random_vectors.sh
 * runs it inside a gcc container for exactly this reason.
 */
#include <cstdint>
#include <cstdio>
#include <limits>
#include <random>

#include "SFMT.h"

#if !defined(__GLIBCXX__)
#error "This generator must be built against libstdc++; other standard libraries use different distribution algorithms."
#endif

namespace
{

/* Mirrors AzerothCore's RandomEngine: SFMT presented as a UniformRandomBitGenerator. */
class SfmtEngine
{
public:
    using result_type = uint32_t;

    explicit SfmtEngine(uint32_t seed) { sfmt_init_gen_rand(&_state, seed); }

    static constexpr result_type min() { return std::numeric_limits<result_type>::min(); }
    static constexpr result_type max() { return std::numeric_limits<result_type>::max(); }

    result_type operator()()
    {
        _draws++;
        return sfmt_genrand_uint32(&_state);
    }

    unsigned long draws() const { return _draws; }

private:
    sfmt_t _state;
    unsigned long _draws = 0;
};

uint32_t bits_of(float value)
{
    uint32_t out;
    __builtin_memcpy(&out, &value, sizeof(out));
    return out;
}

uint64_t bits_of(double value)
{
    uint64_t out;
    __builtin_memcpy(&out, &value, sizeof(out));
    return out;
}

const int COUNT = 12;
const uint32_t SEED = 42;

} // namespace

int main()
{
    printf("{\n");
    printf("  \"_comment\": \"Generated by tools/vectors/generate_random_vectors.cpp against libstdc++. Do not hand-edit.\",\n");
    printf("  \"seed\": %u,\n", SEED);

    /* urand(0, 10000) — the attack table's roll, and the reason urand must be inclusive. */
    {
        SfmtEngine engine(SEED);
        std::uniform_int_distribution<uint32_t> dist(0, 10000);
        printf("  \"urand_0_10000\": [");
        for (int i = 0; i < COUNT; i++)
        {
            printf("%s%u", i ? ", " : "", dist(engine));
        }
        printf("],\n");
        printf("  \"urand_0_10000_draws\": %lu,\n", engine.draws());
    }

    /* irand over a range straddling zero: the unsigned-domain trick has to hold. */
    {
        SfmtEngine engine(SEED);
        std::uniform_int_distribution<int32_t> dist(-50, 50);
        printf("  \"irand_minus50_50\": [");
        for (int i = 0; i < COUNT; i++)
        {
            printf("%s%d", i ? ", " : "", dist(engine));
        }
        printf("],\n");
        printf("  \"irand_minus50_50_draws\": %lu,\n", engine.draws());
    }

    /* frand: one draw per call, via generate_canonical<float, 24>. Emitted as raw bits. */
    {
        SfmtEngine engine(SEED);
        std::uniform_real_distribution<float> dist(0.0f, 1.0f);
        printf("  \"frand_0_1_bits\": [");
        for (int i = 0; i < COUNT; i++)
        {
            printf("%s%u", i ? ", " : "", bits_of(dist(engine)));
        }
        printf("],\n");
        printf("  \"frand_0_1_draws\": %lu,\n", engine.draws());
    }

    /* rand_norm: two draws per call, via generate_canonical<double, 53>. */
    {
        SfmtEngine engine(SEED);
        std::uniform_real_distribution<double> dist;
        printf("  \"rand_norm_bits\": [");
        for (int i = 0; i < COUNT; i++)
        {
            printf("%s%llu", i ? ", " : "", (unsigned long long)bits_of(dist(engine)));
        }
        printf("],\n");
        printf("  \"rand_norm_draws\": %lu\n", engine.draws());
    }

    printf("}\n");
    return 0;
}
