// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowEmu.Data.Db;

#nullable disable

namespace WowEmu.Data.Db.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WowEmu.Data.Db.AccountEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<uint>("Flags")
                        .HasColumnType("int unsigned")
                        .HasColumnName("flags");

                    b.Property<ushort?>("LastBuild")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("last_build");

                    b.Property<string>("LastIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_ip");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("salt");

                    b.Property<byte>("SecurityLevel")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("security_level");

                    b.Property<byte[]>("SessionKey")
                        .HasColumnType("binary(40)")
                        .HasColumnName("session_key");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("username")
                        .UseCollation("utf8mb4_bin");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("verifier");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_account_username");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("WowEmu.Data.Db.BuildInfoEntity", b =>
                {
                    b.Property<ushort>("Build")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("build");

                    b.Property<byte>("BugfixVersion")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("bugfix_version");

                    b.Property<string>("HotfixLetter")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("hotfix_letter");

                    b.Property<byte>("MajorVersion")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("major_version");

                    b.Property<byte>("MinorVersion")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("minor_version");

                    b.HasKey("Build");

                    b.ToTable("build_info", (string)null);

                    b.HasData(
                        new
                        {
                            Build = (ushort)12340,
                            BugfixVersion = (byte)5,
                            HotfixLetter = "a",
                            MajorVersion = (byte)3,
                            MinorVersion = (byte)3
                        });
                });

            modelBuilder.Entity("WowEmu.Data.Db.RealmEntity", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<byte>("AllowedSecurityLevel")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("allowed_security_level");

                    b.Property<ushort>("Build")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("build");

                    b.Property<byte>("Flags")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("flags");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<float>("PopulationLevel")
                        .HasColumnType("float")
                        .HasColumnName("population_level");

                    b.Property<ushort>("Port")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("port");

                    b.Property<byte>("Timezone")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("timezone");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("realmlist", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Address = "127.0.0.1",
                            AllowedSecurityLevel = (byte)0,
                            Build = (ushort)12340,
                            Flags = (byte)0,
                            Name = "WowEmu",
                            PopulationLevel = 0f,
                            Port = (ushort)8085,
                            Timezone = (byte)1,
                            Type = (byte)0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
