-- creature_template — structure
--
-- Vendored from AzerothCore's world database (github.com/azerothcore/database-wotlk), AGPL-3.0.
-- Kept structurally close to upstream on purpose: PLAN.md §5.2 keeps `world` in upstream's shape
-- because 309 tables of community-curated content are not worth re-curating.
--
-- Applied before data/creature_template.sql. Regenerate both with tools/db/export-world.sh.
--
-- Needed by: creature spawning — Creature.Create reads display id, level range, faction, npcflag, unit flags and scale from here.

DROP TABLE IF EXISTS `creature_template`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `creature_template` (
  `entry` mediumint unsigned NOT NULL DEFAULT '0',
  `difficulty_entry_1` mediumint unsigned NOT NULL DEFAULT '0',
  `difficulty_entry_2` mediumint unsigned NOT NULL DEFAULT '0',
  `difficulty_entry_3` mediumint unsigned NOT NULL DEFAULT '0',
  `KillCredit1` int unsigned NOT NULL DEFAULT '0',
  `KillCredit2` int unsigned NOT NULL DEFAULT '0',
  `modelid1` mediumint unsigned NOT NULL DEFAULT '0',
  `modelid2` mediumint unsigned NOT NULL DEFAULT '0',
  `modelid3` mediumint unsigned NOT NULL DEFAULT '0',
  `modelid4` mediumint unsigned NOT NULL DEFAULT '0',
  `name` char(100) NOT NULL DEFAULT '0',
  `subname` char(100) DEFAULT NULL,
  `IconName` char(100) DEFAULT NULL,
  `gossip_menu_id` mediumint unsigned NOT NULL DEFAULT '0',
  `minlevel` tinyint unsigned NOT NULL DEFAULT '1',
  `maxlevel` tinyint unsigned NOT NULL DEFAULT '1',
  `exp` smallint NOT NULL DEFAULT '0',
  `faction` smallint unsigned NOT NULL DEFAULT '0',
  `npcflag` int unsigned NOT NULL DEFAULT '0',
  `speed_walk` float NOT NULL DEFAULT '1' COMMENT 'Result of 2.5/2.5, most common value',
  `speed_run` float NOT NULL DEFAULT '1.14286' COMMENT 'Result of 8.0/7.0, most common value',
  `scale` float NOT NULL DEFAULT '1',
  `rank` tinyint unsigned NOT NULL DEFAULT '0',
  `mindmg` float NOT NULL DEFAULT '0',
  `maxdmg` float NOT NULL DEFAULT '0',
  `dmgschool` tinyint NOT NULL DEFAULT '0',
  `attackpower` int unsigned NOT NULL DEFAULT '0',
  `dmg_multiplier` float NOT NULL DEFAULT '1',
  `baseattacktime` int unsigned NOT NULL DEFAULT '0',
  `rangeattacktime` int unsigned NOT NULL DEFAULT '0',
  `unit_class` tinyint unsigned NOT NULL DEFAULT '0',
  `unit_flags` int unsigned NOT NULL DEFAULT '0',
  `unit_flags2` int unsigned NOT NULL DEFAULT '0',
  `dynamicflags` int unsigned NOT NULL DEFAULT '0',
  `family` tinyint NOT NULL DEFAULT '0',
  `trainer_type` tinyint NOT NULL DEFAULT '0',
  `trainer_spell` mediumint unsigned NOT NULL DEFAULT '0',
  `trainer_class` tinyint unsigned NOT NULL DEFAULT '0',
  `trainer_race` tinyint unsigned NOT NULL DEFAULT '0',
  `minrangedmg` float NOT NULL DEFAULT '0',
  `maxrangedmg` float NOT NULL DEFAULT '0',
  `rangedattackpower` smallint unsigned NOT NULL DEFAULT '0',
  `type` tinyint unsigned NOT NULL DEFAULT '0',
  `type_flags` int unsigned NOT NULL DEFAULT '0',
  `lootid` mediumint unsigned NOT NULL DEFAULT '0',
  `pickpocketloot` mediumint unsigned NOT NULL DEFAULT '0',
  `skinloot` mediumint unsigned NOT NULL DEFAULT '0',
  `resistance1` smallint NOT NULL DEFAULT '0',
  `resistance2` smallint NOT NULL DEFAULT '0',
  `resistance3` smallint NOT NULL DEFAULT '0',
  `resistance4` smallint NOT NULL DEFAULT '0',
  `resistance5` smallint NOT NULL DEFAULT '0',
  `resistance6` smallint NOT NULL DEFAULT '0',
  `spell1` mediumint unsigned NOT NULL DEFAULT '0',
  `spell2` mediumint unsigned NOT NULL DEFAULT '0',
  `spell3` mediumint unsigned NOT NULL DEFAULT '0',
  `spell4` mediumint unsigned NOT NULL DEFAULT '0',
  `spell5` mediumint unsigned NOT NULL DEFAULT '0',
  `spell6` mediumint unsigned NOT NULL DEFAULT '0',
  `spell7` mediumint unsigned NOT NULL DEFAULT '0',
  `spell8` mediumint unsigned NOT NULL DEFAULT '0',
  `PetSpellDataId` mediumint unsigned NOT NULL DEFAULT '0',
  `VehicleId` mediumint unsigned NOT NULL DEFAULT '0',
  `mingold` mediumint unsigned NOT NULL DEFAULT '0',
  `maxgold` mediumint unsigned NOT NULL DEFAULT '0',
  `AIName` char(64) NOT NULL DEFAULT '',
  `MovementType` tinyint unsigned NOT NULL DEFAULT '0',
  `InhabitType` tinyint unsigned NOT NULL DEFAULT '3',
  `HoverHeight` float NOT NULL DEFAULT '1',
  `Health_mod` float NOT NULL DEFAULT '1',
  `Mana_mod` float NOT NULL DEFAULT '1',
  `Armor_mod` float NOT NULL DEFAULT '1',
  `RacialLeader` tinyint unsigned NOT NULL DEFAULT '0',
  `questItem1` int unsigned NOT NULL DEFAULT '0',
  `questItem2` int unsigned NOT NULL DEFAULT '0',
  `questItem3` int unsigned NOT NULL DEFAULT '0',
  `questItem4` int unsigned NOT NULL DEFAULT '0',
  `questItem5` int unsigned NOT NULL DEFAULT '0',
  `questItem6` int unsigned NOT NULL DEFAULT '0',
  `movementId` int unsigned NOT NULL DEFAULT '0',
  `RegenHealth` tinyint unsigned NOT NULL DEFAULT '1',
  `mechanic_immune_mask` int unsigned NOT NULL DEFAULT '0',
  `flags_extra` int unsigned NOT NULL DEFAULT '0',
  `ScriptName` char(64) NOT NULL DEFAULT '',
  `VerifiedBuild` smallint NOT NULL DEFAULT '1',
  PRIMARY KEY (`entry`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Creature System';
/*!40101 SET character_set_client = @saved_cs_client */;
