-- quest_template — structure
--
-- Vendored from AzerothCore's world database (github.com/azerothcore/database-wotlk), AGPL-3.0.
-- Kept structurally close to upstream on purpose: PLAN.md §5.2 keeps `world` in upstream's shape
-- because 309 tables of community-curated content are not worth re-curating.
--
-- Applied before data/quest_template.sql. Regenerate both with tools/db/export-world.sh.
--
-- Needed by: Phase 10 quests.

DROP TABLE IF EXISTS `quest_template`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `quest_template` (
  `ID` mediumint unsigned NOT NULL DEFAULT '0',
  `Method` tinyint unsigned NOT NULL DEFAULT '2',
  `QuestLevel` smallint NOT NULL DEFAULT '1',
  `MinLevel` tinyint unsigned NOT NULL DEFAULT '0',
  `MaxLevel` tinyint unsigned NOT NULL DEFAULT '0',
  `QuestSortID` smallint NOT NULL DEFAULT '0',
  `QuestType` smallint unsigned NOT NULL DEFAULT '0',
  `SuggestedGroupNum` tinyint unsigned NOT NULL DEFAULT '0',
  `LimitTime` int unsigned NOT NULL DEFAULT '0',
  `RequiredClasses` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredRaces` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredSkillId` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredSkillPoints` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredFactionId1` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredFactionId2` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredFactionValue1` mediumint NOT NULL DEFAULT '0',
  `RequiredFactionValue2` mediumint NOT NULL DEFAULT '0',
  `RequiredMinRepFaction` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredMaxRepFaction` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredMinRepValue` mediumint NOT NULL DEFAULT '0',
  `RequiredMaxRepValue` mediumint NOT NULL DEFAULT '0',
  `PrevQuestId` mediumint NOT NULL DEFAULT '0',
  `NextQuestId` mediumint NOT NULL DEFAULT '0',
  `ExclusiveGroup` mediumint NOT NULL DEFAULT '0',
  `NextQuestIdChain` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardXPId` tinyint unsigned NOT NULL DEFAULT '0',
  `RewardOrRequiredMoney` int NOT NULL DEFAULT '0',
  `RewardMoneyMaxLevel` int unsigned NOT NULL DEFAULT '0',
  `RewardSpell` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardSpellCast` int NOT NULL DEFAULT '0',
  `RewardHonor` int NOT NULL DEFAULT '0',
  `RewardHonorMultiplier` float NOT NULL DEFAULT '0',
  `RewardMailTemplateId` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardMailDelay` int unsigned NOT NULL DEFAULT '0',
  `SourceItemId` mediumint unsigned NOT NULL DEFAULT '0',
  `SourceItemCount` tinyint unsigned NOT NULL DEFAULT '0',
  `SourceSpellId` mediumint unsigned NOT NULL DEFAULT '0',
  `Flags` int unsigned NOT NULL DEFAULT '0',
  `SpecialFlags` tinyint unsigned NOT NULL DEFAULT '0',
  `RewardTitle` tinyint unsigned NOT NULL DEFAULT '0',
  `RequiredPlayerKills` tinyint unsigned NOT NULL DEFAULT '0',
  `RewardTalents` tinyint unsigned NOT NULL DEFAULT '0',
  `RewardArenaPoints` smallint unsigned NOT NULL DEFAULT '0',
  `RewardItem1` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardItem2` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardItem3` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardItem4` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardAmount1` smallint unsigned NOT NULL DEFAULT '0',
  `RewardAmount2` smallint unsigned NOT NULL DEFAULT '0',
  `RewardAmount3` smallint unsigned NOT NULL DEFAULT '0',
  `RewardAmount4` smallint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemID1` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemID2` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemID3` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemID4` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemID5` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemID6` mediumint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemQuantity1` smallint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemQuantity2` smallint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemQuantity3` smallint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemQuantity4` smallint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemQuantity5` smallint unsigned NOT NULL DEFAULT '0',
  `RewardChoiceItemQuantity6` smallint unsigned NOT NULL DEFAULT '0',
  `RewardFactionID1` smallint unsigned NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewardFactionID2` smallint unsigned NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewardFactionID3` smallint unsigned NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewardFactionID4` smallint unsigned NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewardFactionID5` smallint unsigned NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewardFactionValue1` mediumint NOT NULL DEFAULT '0',
  `RewardFactionValue2` mediumint NOT NULL DEFAULT '0',
  `RewardFactionValue3` mediumint NOT NULL DEFAULT '0',
  `RewardFactionValue4` mediumint NOT NULL DEFAULT '0',
  `RewardFactionValue5` mediumint NOT NULL DEFAULT '0',
  `RewardFactionOverride1` mediumint NOT NULL DEFAULT '0',
  `RewardFactionOverride2` mediumint NOT NULL DEFAULT '0',
  `RewardFactionOverride3` mediumint NOT NULL DEFAULT '0',
  `RewardFactionOverride4` mediumint NOT NULL DEFAULT '0',
  `RewardFactionOverride5` mediumint NOT NULL DEFAULT '0',
  `PointMapId` smallint unsigned NOT NULL DEFAULT '0',
  `PointX` float NOT NULL DEFAULT '0',
  `PointY` float NOT NULL DEFAULT '0',
  `PointOption` mediumint unsigned NOT NULL DEFAULT '0',
  `LogTitle` text,
  `LogDescription` text,
  `QuestDescription` text,
  `EndText` text,
  `OfferRewardText` text,
  `RequestItemsText` text,
  `QuestCompletionLog` text,
  `RequiredNpcOrGo1` mediumint NOT NULL DEFAULT '0',
  `RequiredNpcOrGo2` mediumint NOT NULL DEFAULT '0',
  `RequiredNpcOrGo3` mediumint NOT NULL DEFAULT '0',
  `RequiredNpcOrGo4` mediumint NOT NULL DEFAULT '0',
  `RequiredNpcOrGoCount1` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredNpcOrGoCount2` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredNpcOrGoCount3` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredNpcOrGoCount4` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredSourceItemId1` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredSourceItemId2` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredSourceItemId3` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredSourceItemId4` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredSourceItemCount1` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredSourceItemCount2` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredSourceItemCount3` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredSourceItemCount4` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredItemId1` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredItemId2` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredItemId3` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredItemId4` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredItemId5` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredItemId6` mediumint unsigned NOT NULL DEFAULT '0',
  `RequiredItemCount1` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredItemCount2` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredItemCount3` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredItemCount4` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredItemCount5` smallint unsigned NOT NULL DEFAULT '0',
  `RequiredItemCount6` smallint unsigned NOT NULL DEFAULT '0',
  `Unknown0` tinyint unsigned NOT NULL DEFAULT '0',
  `ObjectiveText1` text,
  `ObjectiveText2` text,
  `ObjectiveText3` text,
  `ObjectiveText4` text,
  `DetailsEmote1` smallint unsigned NOT NULL DEFAULT '0',
  `DetailsEmote2` smallint unsigned NOT NULL DEFAULT '0',
  `DetailsEmote3` smallint unsigned NOT NULL DEFAULT '0',
  `DetailsEmote4` smallint unsigned NOT NULL DEFAULT '0',
  `DetailsEmoteDelay1` int unsigned NOT NULL DEFAULT '0',
  `DetailsEmoteDelay2` int unsigned NOT NULL DEFAULT '0',
  `DetailsEmoteDelay3` int unsigned NOT NULL DEFAULT '0',
  `DetailsEmoteDelay4` int unsigned NOT NULL DEFAULT '0',
  `EmoteOnIncomplete` smallint unsigned NOT NULL DEFAULT '0',
  `EmoteOnComplete` smallint unsigned NOT NULL DEFAULT '0',
  `OfferRewardEmote1` smallint unsigned NOT NULL DEFAULT '0',
  `OfferRewardEmote2` smallint unsigned NOT NULL DEFAULT '0',
  `OfferRewardEmote3` smallint unsigned NOT NULL DEFAULT '0',
  `OfferRewardEmote4` smallint unsigned NOT NULL DEFAULT '0',
  `OfferRewardEmoteDelay1` int unsigned NOT NULL DEFAULT '0',
  `OfferRewardEmoteDelay2` int unsigned NOT NULL DEFAULT '0',
  `OfferRewardEmoteDelay3` int unsigned NOT NULL DEFAULT '0',
  `OfferRewardEmoteDelay4` int unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quest System';
/*!40101 SET character_set_client = @saved_cs_client */;
