using WowEmu.Core;

namespace WowEmu.Tests.Unit;

/// <summary>
/// Checks the distributions against golden values from AzerothCore's actual stack: SFMT feeding
/// libstdc++'s <c>uniform_int_distribution</c> and <c>uniform_real_distribution</c>, generated by
/// <c>tools/vectors/generate_random_vectors.sh</c>.
/// </summary>
/// <remarks>
/// These tests are about the <b>bit stream</b>, not the statistics. A modulo-based <c>urand</c>
/// would pass any distribution test you could write and still fail here, because it consumes a
/// different number of draws and desynchronises every subsequent roll — which is precisely the
/// failure that would make differential testing against the C++ server useless.
/// <para>
/// The vectors were generated on libstdc++; the standard does not pin these algorithms, and libc++
/// implements <c>uniform_int_distribution</c> differently. Upstream builds against libstdc++, so
/// that is the reference.
/// </para>
/// </remarks>
public sealed class GameRandomTests
{
    private const uint Seed = 42;

    /// <summary>
    /// The attack table's roll. Twelve calls consumed exactly twelve draws in the reference, so any
    /// implementation that draws more or fewer per call will diverge from the second value on.
    /// </summary>
    [Fact]
    public void Urand_MatchesLibstdcxx()
    {
        GameRandom.SeedCurrentThread(Seed);

        uint[] values = new uint[12];
        for (int i = 0; i < values.Length; i++)
        {
            values[i] = GameRandom.Urand(0, 10000);
        }

        Assert.Equal([2667, 3207, 6452, 2756, 4153, 1659, 2150, 7101, 7926, 3843, 5674, 6049], values);
    }

    /// <summary>A range straddling zero, where the unsigned-domain arithmetic has to be exact.</summary>
    [Fact]
    public void Irand_MatchesLibstdcxx_AcrossZero()
    {
        GameRandom.SeedCurrentThread(Seed);

        int[] values = new int[12];
        for (int i = 0; i < values.Length; i++)
        {
            values[i] = GameRandom.Irand(-50, 50);
        }

        Assert.Equal([-24, -18, 15, -23, -9, -34, -29, 21, 30, -12, 7, 11], values);
    }

    /// <summary>
    /// One draw per call, scaled by 2^32. Compared as raw bits so a last-place rounding difference
    /// cannot slip through.
    /// </summary>
    [Fact]
    public void Frand_MatchesLibstdcxx()
    {
        GameRandom.SeedCurrentThread(Seed);

        uint[] bits = new uint[12];
        for (int i = 0; i < bits.Length; i++)
        {
            bits[i] = BitConverter.SingleToUInt32Bits(GameRandom.Frand(0f, 1f));
        }

        Assert.Equal(
            [
                1049136211, 1050947586, 1059400921, 1049436643, 1054122905, 1042935868, 1046231184,
                1060488435, 1061873847, 1053083405, 1058095584, 1058724208
            ],
            bits);
    }

    /// <summary>
    /// Two draws per call. Twelve calls consumed 24 draws in the reference — that ratio is the
    /// thing being pinned down here.
    /// </summary>
    [Fact]
    public void RandNorm_MatchesLibstdcxx()
    {
        GameRandom.SeedCurrentThread(Seed);

        ulong[] bits = new ulong[12];
        for (int i = 0; i < bits.Length; i++)
        {
            bits[i] = BitConverter.DoubleToUInt64Bits(GameRandom.RandNorm());
        }

        Assert.Equal(
            [
                4599448455307399562, 4598637273786436406, 4595147196880726246, 4604570659501564357,
                4600595114164927022, 4603623497387878460, 4605341138327502228, 4605921248816643973,
                4604364647689709832, 4606923242120900520, 4560093221751606732, 4605268006831151384
            ],
            bits);
    }

    /// <summary>
    /// <c>rand_norm</c> is defined as two draws; if it were one, the stream after any call would
    /// shift by a word. This pins the count directly rather than inferring it.
    /// </summary>
    [Fact]
    public void RandNorm_ConsumesExactlyTwoDraws()
    {
        GameRandom.SeedCurrentThread(Seed);
        GameRandom.RandNorm();
        uint afterRandNorm = GameRandom.Rand32();

        GameRandom.SeedCurrentThread(Seed);
        Sfmt19937 reference = new(Seed);
        reference.NextUInt32();
        reference.NextUInt32();

        Assert.Equal(reference.NextUInt32(), afterRandNorm);
    }

    [Fact]
    public void Frand_ConsumesExactlyOneDraw()
    {
        GameRandom.SeedCurrentThread(Seed);
        GameRandom.Frand(0f, 1f);
        uint afterFrand = GameRandom.Rand32();

        Sfmt19937 reference = new(Seed);
        reference.NextUInt32();

        Assert.Equal(reference.NextUInt32(), afterFrand);
    }

    /// <summary>
    /// <c>urand</c> is inclusive at both ends. The melee attack table rolls <c>urand(0, 10000)</c>
    /// and needs all 10001 outcomes; an exclusive bound silently shifts every combat threshold.
    /// </summary>
    [Fact]
    public void Urand_IsInclusiveAtBothEnds()
    {
        GameRandom.SeedCurrentThread(7);

        bool sawMin = false;
        bool sawMax = false;

        for (int i = 0; i < 20000 && (!sawMin || !sawMax); i++)
        {
            uint value = GameRandom.Urand(10, 12);
            Assert.InRange(value, 10u, 12u);

            sawMin |= value == 10;
            sawMax |= value == 12;
        }

        Assert.True(sawMin, "urand never returned its minimum");
        Assert.True(sawMax, "urand never returned its maximum");
    }

    [Fact]
    public void Urand_WithEqualBounds_ReturnsThatValue()
    {
        GameRandom.SeedCurrentThread(Seed);
        Assert.Equal(5u, GameRandom.Urand(5, 5));
    }

    /// <summary>The full 32-bit range takes the no-rejection path: one draw, returned unchanged.</summary>
    [Fact]
    public void Urand_OverFullRange_ReturnsRawDraw()
    {
        GameRandom.SeedCurrentThread(Seed);
        uint value = GameRandom.Urand(0, uint.MaxValue);

        Assert.Equal(new Sfmt19937(Seed).NextUInt32(), value);
    }

    [Fact]
    public void Irand_IsInclusiveAtBothEnds()
    {
        GameRandom.SeedCurrentThread(3);

        bool sawMin = false;
        bool sawMax = false;

        for (int i = 0; i < 20000 && (!sawMin || !sawMax); i++)
        {
            int value = GameRandom.Irand(-1, 1);
            Assert.InRange(value, -1, 1);

            sawMin |= value == -1;
            sawMax |= value == 1;
        }

        Assert.True(sawMin && sawMax);
    }

    [Fact]
    public void RandNorm_StaysBelowOne()
    {
        GameRandom.SeedCurrentThread(Seed);

        for (int i = 0; i < 10000; i++)
        {
            double value = GameRandom.RandNorm();
            Assert.InRange(value, 0.0, 0.9999999999999999);
        }
    }

    [Fact]
    public void RandChance_IsRandNormScaledToPercent()
    {
        GameRandom.SeedCurrentThread(Seed);
        double chance = GameRandom.RandChance();

        GameRandom.SeedCurrentThread(Seed);
        double norm = GameRandom.RandNorm();

        Assert.Equal(norm * 100.0, chance);
    }

    [Fact]
    public void Urand_Throws_WhenMaxBelowMin()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => GameRandom.Urand(5, 4));
        Assert.Throws<ArgumentOutOfRangeException>(() => GameRandom.Irand(1, -1));
    }

    [Fact]
    public void SeedCurrentThread_MakesTheStreamReproducible()
    {
        GameRandom.SeedCurrentThread(99);
        uint[] first = [GameRandom.Rand32(), GameRandom.Rand32(), GameRandom.Rand32()];

        GameRandom.SeedCurrentThread(99);
        uint[] second = [GameRandom.Rand32(), GameRandom.Rand32(), GameRandom.Rand32()];

        Assert.Equal(first, second);
    }
}
