<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WowEmu.Cryptography\WowEmu.Cryptography.csproj" />
    <ProjectReference Include="..\..\src\WowEmu.Core\WowEmu.Core.csproj" />
    <ProjectReference Include="..\..\src\WowEmu.Protocol\WowEmu.Protocol.csproj" />
    <ProjectReference Include="..\..\src\WowEmu.AuthServer\WowEmu.AuthServer.csproj" />
    <ProjectReference Include="..\..\src\WowEmu.Network\WowEmu.Network.csproj" />
    <ProjectReference Include="..\..\src\WowEmu.WorldServer\WowEmu.WorldServer.csproj" />
    <ProjectReference Include="..\..\src\WowEmu.Data.Client\WowEmu.Data.Client.csproj" />
    <ProjectReference Include="..\..\src\WowEmu.Game\WowEmu.Game.csproj" />
  </ItemGroup>

</Project>